src/dispatchers.ts

The update to use Image constructor instead of URL for icon has broken out storage of the data, resulting in bad data in the DB and errors when rehydrating it. Long term I would like to move back to using URL for the `icon` property as this is simpler to work with.

Fixed errors when loading bad data from the DB

---

package.json
src/app.ts
src/constants.ts
src/dispatchers.ts
src/handlers.ts
src/user.ts
yarn.lock

refs [MOM-300](https://linear.app/tryghost/issue/MOM-300/update-actor-data-with-ghost-site-settings#comment-4e49803f)
Implemented Ghost site changed webhook handler so that when the settings for a Ghost instance are updated, the actor data is also updated in the database (name, description, icon). For this to work, the Ghost instance needs to setup a webhook for the `Site Changed` event and point it to the `<host>/.ghost/activitypub/webhooks/site/changed` endpoint

Implemented Ghost site changed webhook handler

---

package.json
src/app.ts
src/dispatchers.ts
src/user.ts
yarn.lock

This includes the new inbox queue, which means that inbox handlers receive a Context instead of RequestContext

Updated @fedify/fedify to 0.13.0-dev.316

---

src/handlers.ts

ref https://linear.app/tryghost/issue/MOM-329
The `to` field for Create<Article> activities was incorrectly set to the
followers collection, but the content is intended to be public. This may have
been causing issues with users being able to see the content depending on if
they are following the actor.
What we've fixed here is made public activities addressed `to` the public
collection, and adding a `cc` to the followers because they are also an
intended recipient, though not the primary.
Using a shared inbox make for less network requests when delivering activities
and increases performance in terms of both load on the server as well as
delivery times because recipients on the same server can all be informed by the
same request

Correct addressing

---

src/app.ts
src/dispatchers.ts
src/handlers.ts
yarn.lock

Added announce handling
refs [MOM-280](https://linear.app/tryghost/issue/MOM-280/handle-incoming-announces)

Added announce handling

---

src/dispatchers.ts

This is needed to render the original author of the object in the frontend

Hydrated `attributedTo` property of Announce objects

---

cucumber.js
docker-compose.yml
features/create-article-from-post.feature
features/handle-create-article.feature
features/step_definitions/stepdefs.js
package.json
src/app.ts
src/handlers.ts
yarn.lock

[WIP] Fix creating articles

---

features/outbox.feature
features/step_definitions/stepdefs.js
src/dispatchers.ts

refs [AP-359](https://linear.app/tryghost/issue/AP-359/filter-outbox-activities-to-create-and-announce)
Filtered outbox activities to only include `Create` and `Announce` activities
which seems to be inline with what other implementations are doing (i.e Mastodon)

Filtered outbox activities to only include `Create` and `Announce` activities

---

features/handle-like.feature
features/step_definitions/stepdefs.js
src/app.ts
src/dispatchers.ts

refs [AP-283](https://linear.app/tryghost/issue/AP-283/handle-incoming-likes)
Added handler for incoming likes that adds the like activity to the actors inbox and persists any relevant data to the database.

Added handler for incoming likes

---

src/app.ts
src/dispatchers.ts
src/handlers.ts
src/lookup-helpers.ts
src/user.ts
src/user.unit.test.ts

🍦 
We got a few things happening here!
We're adding a liked collection to actors, this is so that we can render a list of the liked content in the Admin. The liked collection functions similar to how we're doing the inbox and outbox, we're storing an array of the ids belonging to the collection.
We've got some basic object dispatchers wired up for `Like` and `Undo` which is necessary so that we can generate id's for those objects.
The inbox handler has been updating to attached a `liked` property to the `object` of the activity, this allows us to render the item correctly in the frontend with a filled in heart. I didn't store the `liked` property on the object, because of concerns of losing the data - e.g. if we start handling `Update` activities and we overwrite the object in the DB - we …

[WIP] Sending & Un-sending Likes

---

src/knex.kvstore.ts

refs [AP-354](https://linear.app/tryghost/issue/AP-354/remove-redundant-key-update-in-update-queries)
Removed redundant key update in update statement that could be causing wait locks in the database

Removed redundant key update

---

src/app.ts
src/handlers.ts

refs [AP-377](https://linear.app/tryghost/issue/AP-377/inbox-returning-33mb-of-data)
Added a new endpoint for retrieving activities for a given actor:
```
GET /.ghost/activitypub/activities/:handle?limit=<number>&cursor=<string>
```
At the moment this returns the same data as the inbox handler but in the future we are likely to want to augment this with additional data (i.e including the actor's own activities). This endpoint is designed to be used by the activity pub UI in Ghost Admin and not other activity pub compliant servers / clients.
The returned data is paginated using cursor based pagination. The `cursor` query parameter is optional and is used to fetch the next page of activities. The `limit` query parameter is also optional and is used to limit the number of activities returned …

Added dedicated endpoint for retrieving activities for a given actor

---

src/db.ts
src/handlers.ts

refs [AP-377](https://linear.app/tryghost/issue/AP-377/inbox-returning-33mb-of-data), [TryGhost/ActivityPub#40](https://github.com/TryGhost/ActivityPub/pull/40)
Added a new query parameter `includeOwn` to the activities endpoint. When set to `true`, the endpoint will also return all activites performed by the user.

Allow activities endpoint to include own activities

---

src/db.ts
src/handlers.ts

no refs
In order for client-side pagination to work effectively, the activities endpoint has been updated to:
- Handle filtering required on the client-side (was previously done client-side)
- Return nested replies in returned activities
- Expand `inReplyTo` to full object

Updated activities endpoint to better support client-side pagination

---

src/api/action/search.ts
src/api/index.ts
src/app.ts
src/helpers/activitypub/actor.ts
src/helpers/activitypub/actor.unit.test.ts
src/helpers/sanitize.ts
src/helpers/sanitize.unit.test.ts
src/helpers/uri.ts
src/helpers/uri.unit.test.ts

refs [AP-352](https://linear.app/tryghost/issue/AP-352/search-for-mastodon-usernames-in-ghost-admin)
Added a new endpoint to enable searching for Fediverse users by their handle or URL

Added endpoint for searching for Fediverse users

---

src/api/action/profile/getFollowers.ts
src/api/action/profile/getFollowing.ts
src/api/action/search.ts
src/api/index.ts
src/app.ts
src/helpers/activitypub/actor.ts
src/helpers/activitypub/actor.unit.test.ts

refs [AP-442](https://linear.app/tryghost/issue/AP-442/add-dynamic-following-followers-to-search-result-profile), [TryGhost/Ghost#21170](https://github.com/TryGhost/Ghost/pull/21170)
Added endpoints for retrieving profile following / followers

Added endpoints for retrieving profile following / followers

---

src/api/action/getActivities.ts
src/db.ts

refs [AP-477](https://linear.app/ghost/issue/AP-477/incorrect-posts-in-home-feed)
Added functionality to filter out non-follower activity when the `excludeNonFollower` query param is set to true

Added functionality to filter out non-follower activity

---

src/dispatchers.ts

refs [AP-473](https://linear.app/ghost/issue/AP-490/following-does-not-show-all-of-following)
Changed following dispatcher to return all types of followers and not just `Person`

Changed following dispatcher to return all types of followers

---

src/app.ts
src/handlers.ts

refs [AP-489](https://linear.app/ghost/issue/AP-489/followers-showing-unknown-on-user-profile)
Added temporary endpoint to retrieve expanded followers list as the regular followers endpoint only return the ids of the followers and not the full object (which is required by the client). Once we have a better way to query for this information, we can remove this endpoint.

Added temporary endpoint to retrieve expanded followers list

---

.github/workflows/build.yml
docker-compose.yml

- interval of 300s means it'll only check every 5 minutes, which is WAY too slow for us
- we can just do with checking every second and increasing the number of retries
- this cuts 5 mins from CI time

Fixed docker-compose interval period

---

.github/workflows/build.yml

- this is only useful if we want to do multi-arch build and layer caching, but right now, the layer caching is slower than pulling it fresh every time, due to overhead
- this also avoids the delay from the `docker-container` driver having to import the layers into Docker

Removed Docker Buildx

---

src/app.ts

- we didn't hook up any HTTP server middleware to Sentry, so we've been missing some alerts in Sentry
- Hono does have some Sentry middleware, but I'd like to investigate it some more
- for now, we can add an `onError` handler and manually send the error to Sentry

Fixed sending application errors to Sentry

---

Dockerfile

- we can remove the yarn cache after installing dependencies, which cuts 900MB from the image size

Shrunk Docker images by removing Yarn cache

---

docker-compose.yml

- without this change, we're always writing the file even if the healthcheck fails

Fixed writing healthcheck file until after successful check

---

features/step_definitions/stepdefs.js

refs [AP-526](https://linear.app/ghost/issue/AP-526/implement-pagination-for-fedify-collections)
The changes made to add pagination to the collections were not reflected in the cucumber tests. This commit updates the tests to reflect the changes.

Fixed failing cucumber tests

---

package.json

refs https://ghost.slack.com/archives/C06TE92R3JR/p1730199912121529
- if `cucumber-tests` fails (ie. tests fail), `docker-compose` doesn't set the exit code correctly, so we don't know when the tests fail
- this fixes that by using `--exit-code-from <container>`, which seems to be the recommended way

Fixed getting exit code from child container

---

package.json
yarn.lock

ref https://github.com/dahlia/fedify/releases/tag/1.2.0
- bumps internal logtape to 0.7.1, which allows for implicit contexts

Updated Fedify to v1.2.0

---

migrate/Dockerfile

- switched to `bookworm-slim` for smaller initial size
- removed apt cache after we're done with it
- this shrinks the image size by about 100MB and increases `dive` image efficiency to 99%

Optimized migrations image size

---

src/api/action/profile/get.ts
src/api/action/profile/getFollowers.ts
src/api/action/profile/getFollowing.ts
src/api/action/search.ts
src/dispatchers.ts
src/handlers.ts
src/lookup-helpers.ts

refs https://linear.app/ghost/issue/AP-533
Threads requires authenticated fetch when interacting with their API, which is something we should default to, for now we've added a helper, but this should eventually be opt-out rather than opt-in

Looked up remote objects with authenticated fetch

---

src/api/action/getActivities.ts
src/api/action/getActivityThread.ts
src/api/index.ts
src/app.ts
src/db.ts
src/helpers/activitypub/activity.ts

refs:
- https://linear.app/ghost/issue/AP-439/seeing-parent-post-for-replies
- https://linear.app/ghost/issue/AP-481/reply-ui
- https://linear.app/ghost/issue/AP-482/replies-to-a-post-should-be-visible-when-opening-it
Implemented thread retrieval so that replies can be displayed in a thread by the client. This is done by adding a new endpoint to the API that retrieves the thread of a given activity
The thread returned is an array of activities ordered in chronological order - The first being the root activity and the last being the last reply
This also removes the existing replies implementation as it is no longer needed

Implemented thread mechanism for replies

---

features/handle-announce.feature
features/handle-like.feature
features/handle-replies.feature
features/like-activity.feature
features/step_definitions/stepdefs.js
src/dispatchers.ts
src/helpers/user.ts

closes https://linear.app/ghost/issue/AP-545
Previously we were adding all incoming messages in our inbox to our inbox, now
we restrict it to only people we're following. We do still store the object in
the global db - but we maybe be able to optimise this in future.
We're only restricting Create and Announce activities at the moment. We expect
to receive Likes from Actors we don't follow, as well as Follow activities too!

Restricted inbox to following

---

package.json
src/app.ts
yarn.lock

- this middleware seems to drop sourcemaps and doesn't really do deep integration for requests, so implementing it ourselves seems like a better option

Reverted Hono Sentry integration

---

src/app.ts
src/helpers/request-data.ts

- this adds the request metadata to Sentry by coercing it from a Request into a PolymorphicRequest that Sentry expects
- this means we get metadata in Sentry about the request and where it came from

Added commit metadata to Sentry reports

---

src/dispatchers.ts

- we needed some more exception collection statements because these errors were going missing

Added more Sentry exception collection

---

src/handlers.ts

refs https://linear.app/ghost/issue/AP-523
The `object` property of the Follow activity doesn't contain the same serialised data that a serialised Actor does, which means we can't reuse it in the following collection in the frontend state management. For now we'll return the Actor instead so we can update the frontend without waiting for an Accept

Returned followed Actor from follow action

---

src/api/action/getActivities.ts
src/api/action/getActivityThread.ts
src/api/action/profile/getFollowers.ts
src/api/action/profile/getFollowing.ts
src/api/action/search.ts

no refs
Updated the API endpoints to consistently use the same method of URL encoding ( previously we used `encodeURIComponent` in some places and base64 encoding in others). This change ensures that all endpoints use `encodeURIComponent` to encode URL parameters.
This change also normalises the naming of the `cursor` parameter in the endpoints - `cursor` and `next` are now used consistently across all endpoints

Ensured consistent URL encoding in the endpoints

---

src/dispatchers.ts
src/dispatchers.unit.test.ts

refs [AP-485](https://linear.app/ghost/issue/AP-485/add-nodeinfo-endpoint)
Updated the `software.version` property to `0.1.0` for the response returned by the `nodeinfo` endpoint to better reflect the current state of the software (currently under development)

Updated `nodeinfo` software version to `0.1.0`

---

src/app.ts
src/helpers/context-header.ts

refs https://www.w3.org/TR/trace-context/
refs https://cloud.google.com/trace/docs/trace-context
- this is preferred over `x-cloud-trace-context` as it's a standard and not GCP-specific

Switched to using `traceparent` header for tracing

---

src/app.ts

ref https://linear.app/ghost/issue/AP-555/add-requestdb-tracing-to-activitypub
- this allows us to differentiate parts of the stack easier

Added `service.name` attribute to tracing spans

---

.github/workflows/build.yml

- these are set in the infra Terraform setup so we can avoid redefining them here too

Removed env vars from migration job

---

src/app.ts

- this allows us to see how long the process is taking to initialize

Added boot time to logging output

---

src/instrumentation.ts

- we only really need one of these modules at any one time, so we can just lazyload them and speed up boot time

Lazyloaded instrumentation modules

---

docker-compose.yml

- this mapped port collided with the one for the non-testing emulator, so it caused Docker to complain

Fixed port assignment for Pub/Sub emulator

---

src/app.ts

ref https://linear.app/ghost/issue/AP-551
We are unable to replicate some issues locally and would like to enable more specific logs in production, rather than having to change the hardcoded values we should be able to do this via the enviroment.
This adds support for three new environment variables:
- `LOG_LEVEL_FEDIFY` sets the log level for internal fedify logs
- `LOG_LEVEL_ACTIVITYPUB` sets the log level for our logs
- `LOG_LEVEL` is a fallback if either of the above are not set
If none of these are set we continue to default to the existing hardcoded values.

Added support for configuring log level with env

---

.gitignore
Dockerfile
docker-compose.yml
package.json
yarn.lock

ref https://linear.app/ghost/issue/AP-550/overhaul-docker-testing-setup
- with this change, we do away with `tsx` in favor of straight `esbuild`, as `tsx` was proving to be problematic with our boot time
- we can just compile this to a single JS file to keep this fast
- this also changes the Docker workflow to use this and concurrently to watch and reload the files

Switched to `esbuild` and bundle code into single file

---

docker-compose.yml
package.json

ref https://linear.app/ghost/issue/AP-550/overhaul-docker-testing-setup
- made `activitypub` rely on `migrate` so we run migrations in dev
- fixed `yarn fix` actually removing the images
- `yarn dev` will now try and recreate the containers, which will often no-op, but they'll be updated if the package.json changes

Improved Docker workflow

---

src/app.ts

- Sentry should continue to use the same trace ID so we can link together traces and logs in GCP

Configured Sentry to continue using the same trace

---

src/instrumentation.ts

- for some reason, I think the resource filter is filtering out our traces in GCP, so I need to allow all of them so it's easier to debug
- also fixed registering the provider twice

Enabled all resources to export to GCP

---

src/instrumentation.ts

- for some reason, Sentry is disabling OTel unless you enable tracing in Sentry, I don't know why
- to workaround that, we can enable tracing but disable all the integrations

Added workaround for Sentry disabling OTel

---

src/instrumentation.ts

ref https://github.com/TryGhost/ActivityPub/commit/070a35a2717e75951ff30efd53e8e8c56e8d2831
- this should have been a little more obvious, it was because of the ordering in our code, we should set up OTel before Sentry

Fixed root cause of workaround

---

src/db.ts

refs [AP-579](https://linear.app/ghost/issue/AP-579/investigate-parent-post-visibility-issues-in-replies-to-articles)
Updated the query for retrieving thread parents / children so that it takes into account the activity type. This is needed because when we query on the object it is possible for there to be multiple activities with a matching object if the actvity embeds the object (i.e in the case of a `Like` activity). This is important when looking up the immediate parent of an activity (as we only expect there to be 1 parent). Scoping the type of activity should be fine for our use case of "threads" (a list of comments)

Updated query for retrieving thread parents / children

---

src/db.ts

- the default of 10 is too small for this instance and it looks like we're running into stalled requests
- by increasing this, we should be able to get more throughput to the DB, and still stay under the connection limit imposed by Cloud SQL

Increased DB connection pool size

---

src/helpers/activitypub/activity.ts

- in the case where the actor and the item's actor are the same person, we should avoid the lookup because it can be expensive

Optimized looking up actors when building activity

---

.github/workflows/build.yml

- added `workflow_dispatch` so we can trigger manually
- added `pull_request` so we get CI on PRs
- configured `push` to only run on `main`
- this prevents random (non-PR) branches from being tested, but that's good because it reduces noise

Updated CI workflow triggers

---

src/db.ts

- this reverts commit f3429e49469bf3f45e2e627adeb6bdf11e90c492
- this suspiciously aligns with the start of a memory leak

Reverted "Increased DB connection pool size"

---

src/db.ts

- this helps with performance because it allows requests that produce a large number of DB requests to fire off more requests at once

Increased max DB pool size

---

src/app.ts
src/helpers/context-header.ts

ref https://linear.app/ghost/issue/AP-603/logging-and-debugging-improvements
- this adds support for the `sampled` / `traceSampled` flag in trace spans, which allows us to propagate whether a span is being sampled or not

Added support for sampled flag on trace contexts

---

src/dispatchers.ts

- we no longer need to cast these to `any`

Cleaned up a couple of `any` instances

---

src/app.ts

no refs
When using the message queue in production we was finding that seemingly randomly, activities would be attributed to the the wrong site. We narrowed this down to the fact that the scoped kvstore was not being reinitialised on each incoming message. Fedify reuses contexts when queueing messages so its possible that the already initialised scoped kvstore was being used for a different site. This change ensures that the scoped kvstore gets reinitialised on each incoming message.

Ensured scoped kvstore is reinitialised on each incoming message

---

package.json
yarn.lock

ref https://linear.app/ghost/issue/AP-597
There was a bug in fedify when loading the outbox for an Actor if the outbox was the type of OrderedCollectionPage. This was causing our code to throw an error when loading their profile as we would fetch their outbox to get the recent activities. This bug was fixed in v1.2.6 of fedify.

Fixed loading profiles for actors from wordpress plugin

---

nginx/nginx.conf
nginx/server.conf

- you can set these on the top-level `http` object and they get passed down, which means we can avoid duplication

Deduplicated Nginx config

---

src/api/action/getActivities.ts
src/db.ts

no refs
The query for retrieving `activityMeta` needed to be updated to factor in that `inReplyTo` on an object can be a string OR an object

Fixed `:noReply` filter not filtering replies when retrieving activities

---

cucumber.js
docker-compose.yml
docker/cucumber-tests
package.json

no refs
This change allows you to run only tagged scenarios when executing cucumber. This is useful when you want to run only a subset of scenarios
```
yarn test:cucumber '@only'
```
```
yarn test:cucumber '@foo and @bar'
```
```
yarn test:cucumber '@foo or @bar'
```

Added ability to run tagged cucumber scenarios

---

package.json

- this should give us the unbundled source files of the AP code

Enabled sourcemaps in Esbuild

---

features/accept-follows.feature
features/create-note.feature
features/follow-account.feature
features/handle-announce.feature
features/handle-create-article.feature
features/handle-group-announce.feature
features/handle-like.feature
features/handle-replies.feature
features/like-activity.feature
features/step_definitions/stepdefs.js
src/dispatchers.ts

refs [AP-608](https://linear.app/ghost/issue/AP-608/ghost-does-not-work-with-lemmy-or-wordpress)
Added handling for `Group` announced `Create` activities so that these activities are processed by the service. Activities are usually only announced as part of Group federation
See https://codeberg.org/fediverse/fep/src/branch/main/fep/1b12/fep-1b12.md for more details

Added handling for `Group` announced `Create` activities

---

.editorconfig
features/accept-follows.feature
features/create-note.feature

Formatted feature files for consistency

---

docker/cucumber-tests
migrate/bin/up
pubsub/start.sh
scripts/bin/populate-activitypub-db

Formatted scripts for consistency

---

src/constants.ts

no refs
Reduced the number of items that are returned when fetching an activitpub collection page

Reduced size of activitypub collection page

---

src/app.ts

ref https://linear.app/ghost/issue/AP-635/error-invalid-authorization-header
- in the case we aren't passed a valid Authorization header, we currently throw errors
- throwing an error will return in a 500, but we actually want a HTTP 401
- this also changes several other places where we throw errors to return HTTP status codes instead
- also adds logging so we can have visibility on why things are occurring

Fixed handling of missing Host and invalid Authorization headers

---

package.json
yarn.lock

closes https://linear.app/ghost/issue/AP-551
Fedify previously would not process the same activity twice based on the activity id, but this meant that if it was delivered to two different hosts managed by the same server instance that only the first one would be processed.
This has been updated in fedify 1.3.1 to include the origin of the request in the cache key for idempotency checks.

Fixed multi tenant handling of inboxes

---

docker-compose.yml
features/followers.feature
features/step_definitions/stepdefs.js
src/constants.ts
src/dispatchers.ts
src/dispatchers.unit.test.ts

refs [AP-638](https://linear.app/ghost/issue/AP-638/ghost-is-not-delivering-activities-to-all-followers)
Added logic to ensure that activities are delivered to all followers and not just the first page of followers

Ensured activities are delivered to all followers

---

features/step_definitions/stepdefs.js
src/app.ts
src/handlers.ts
src/helpers/activitypub/actor.ts
src/helpers/activitypub/actor.unit.test.ts
src/helpers/user.ts
src/helpers/user.unit.test.ts

ref https://linear.app/ghost/issue/AP-592
When we fetch the site data we'll attempt to update the site actor too, this
will ensure that when Ghost boots any changes are propagated to us.
We're handling the sending of the Update activity ourself, and there's room to
remove duplication here. I'd like to think about what pattern we use for this.
Ideally I think a repository would be responsible for this or at least abstract
it.

Added support for updating the site actor

---

cucumber.js
docker-compose.yml
docker/cucumber-tests

no refs
Misc cucumber tweaks:
- Use `docker compose run` instead of `docker compose up` to get a `TTY` for live updating of progress + colorization of output. Also removes the annoying service name prefix from the output (making it easier to copy/paste undefined snippets)
- Use `progress` as the formatter so we can see that things are happening
- Use JS based config instead of cmd line args
- Added `failFast` to the config so we can stop on the first failure
- Use `cucumber-js` bin directly to prevent double `yarn run` output at the end of the run

Misc cucumber tweaks

---

features/create-article-from-post.feature
features/step_definitions/stepdefs.js
src/handlers.ts

closes https://linear.app/ghost/issue/AP-551
It's possible that posts have `null` for their `html` and `excerpt` properties, and we weren't handling that, resulting in errors!

Allowed `null` for `html` and `excerpt` on posts

---

src/dispatchers.ts

Some ActivityPub implementions, threads.net as one example, require the use of authorized fetch to read objects, even if they are public.
When we use the `getObject` method of the Activity class the request is made without authorized fetch, which causes the handler to error.
Our lookupObject helper handles the authorized fetch component, which fixes the error.

Handle authorized fetch for announced objects

---

features/create-article-from-post.feature
features/handle-replies.feature
features/step_definitions/stepdefs.js
package.json
yarn.lock

no refs
Refactored cucumber webhook scenarios:
- Tweaked wording slightly - Removed `valid` as it is superfluous
- Added the ability to define the webhook payload in the scenario (gherkin)
- Added helper to wait for an activity type in the outbox (similar to existing logic for waiting for a known activity in the outbox)
- Made webhook fixture dynamic to avoid unexpected test results

Refactored cucumber webhook scenarios

---

biome.json
src/activitypub/activity.ts
src/activitypub/activity.unit.test.ts
src/activitypub/actor.ts
src/activitypub/actor.unit.test.ts
src/activitypub/index.ts
src/activitypub/object.ts
src/activitypub/object.unit.test.ts
src/activitypub/outbox.ts
src/activitypub/outbox.unit.test.ts
src/activitypub/uri.ts
src/activitypub/uri.unit.test.ts
src/app.ts
src/http/api/webhooks.ts
src/publishing/__snapshots__/service/create.json
src/publishing/helpers.ts
src/publishing/service.ts
src/publishing/service.unit.test.ts

no refs
This is being done as a pre-requisite to handling publishing posts containing member content from Ghost
Me & @allouis discussed taking the opportunity to refactor this area of the codebase to make it more modular / testable and reducing the tight coupling between the http handler and the business logic for publishing posts
In this refactored design:
- The webhook post published http handler now only deals with only validating the incoming data & returning the appropriate response. It passes the validated data to a new service that deals with the publishing
- The new publishing service contains all the business logic for publishing a post. In the future we can move the logic for publishing a reply / note here as well to keep all the publishing logic co-located (and also cleaning up …

Refactor webhook post published handling into a more modular structure

---

src/http/api/webhooks.ts
src/publishing/helpers.ts
src/publishing/service.ts
src/publishing/service.unit.test.ts
src/publishing/types.ts

refs [AP-641](https://linear.app/ghost/issue/AP-641/only-public-posts-should-be-sent-to-the-fediverse)
Ensured that only public content is posted when the visibility of an incoming post is not `public`

Ensure only public content is posted

---

src/app.ts
src/http/api/accounts.ts
src/http/api/index.ts

refs [AP-647](https://linear.app/ghost/issue/AP-648/refactor-profile-tab-to-use-account-and-follows)
Added API endpoints for retrieving the current users account and follows so that the UI can be refactored to use these endpoints instead of the ActivityPub endpoints directly. This lets us iteratively move towards utilising the new database schema for retrieving account and follows data

Added API endpoints for retrieving the current users account and follows

---

features/step_definitions/stepdefs.js
src/dispatchers.ts
src/dispatchers.unit.test.ts

refs [AP-649](https://linear.app/ghost/issue/AP-649/update-activitypub-follows-and-following-collections-to-only-return)
Updated `following` and `followers` collection to only return URLs in preparation for the upcoming changes around storing `accounts`. We return just the minimal information required for the `following` and `followers` collections so we can reduce the amount of data we need to store

Updated `following` and `followers` collection to only return URLs

---

src/http/api/accounts.ts

no refs
Updated account response
- `postsCount` → `postCount`
- `url` now returns the correct URL

Updated account response

---

src/dispatchers.ts
src/dispatchers.unit.test.ts

no refs
Added `sharedInboxUrl` to followers dispatcher output so that the Fedify can send an activity to the shared inbox of a follower

Added `sharedInboxUrl` to followers dispatcher output

---

src/account/account.service.integration.test.ts
src/account/account.service.ts
src/account/types.ts
src/constants.ts

Implement account service that will be utilised throughout the application when dealing with accounts

Implement account service

---

package.json
src/app.ts
src/db.ts
src/handlers.ts
src/site/site.service.integration.test.ts
src/site/site.service.ts

This replaces the use of the `getSite` helper and moves towards our new structure, paving the way for the initialisation of users and accounts for sites upon init.

Wired up SiteService

---

src/account/account.service.integration.test.ts
src/account/account.service.ts
src/account/utils.ts
src/account/utils.unit.test.ts
src/app.ts
src/dispatchers.ts

refs [AP-661](https://linear.app/ghost/issue/AP-661/update-incoming-follow-activity-handler-to-record-data-in-the-new)
Updated incoming `Follow` activity handler to record data in the new follows table. The original logic for writing to the kv store is kept in place until we have fully migrated to th e new table.

Updated incoming `Follow` activity handler to record data in the new follows table

---

package.json

Ours tests currently do some DB teardown and intefer with each other if they're run in parallel.

Ensured that tests run in series

---

src/account/account.service.integration.test.ts
src/site/site.service.integration.test.ts

no refs
Improved performance of integration tests by stubbing `generateKeyPair` as it is a slow operation

Improved performance of integration tests

---

src/app.ts
src/dispatchers.ts
src/http/api/accounts.ts

refs [AP-681](https://linear.app/ghost/issue/AP-681/update-followers-and-following-counters-to-read-data-from-the-new)
Updated `followers` and `following` counters to read data from the `follows` table

Updated `followers` and `following` counters to read data from the `follows` table

---

features/step_definitions/stepdefs.js
src/account/account.service.integration.test.ts
src/account/account.service.ts
src/app.ts
src/handlers.ts

refs [AP-655](https://linear.app/ghost/issue/AP-664/update-api-follow-action-to-record-data-in-the-new-follows-table)
Updated follow action to use `follows` table when checking if already following

Updated follow action to use `follows` table when checking if already following

---

src/account/account.service.integration.test.ts
src/account/account.service.ts
src/app.ts
src/dispatchers.ts
src/dispatchers.unit.test.ts
src/http/api/accounts.ts
src/site/site.service.integration.test.ts
src/site/site.service.ts

Whilst we were building out the infrastructure for accounts and sites we ended up with some duplicate code, this consolidates it into the account service, slightly updating the signature to never resolve with null, throwing if an account is not found instead. We also clean up all the call sites and tests.

Removed duplicate method for fetching default account

---

src/app.ts
src/dispatchers.ts
src/helpers/activitypub/actor.ts
src/helpers/activitypub/actor.unit.test.ts
src/http/api/accounts.ts
src/http/api/follows.ts
src/http/api/profiles.ts
src/http/api/search.ts

no refs
Updated application to use `isFollowedByDefaultSiteAccount` to determine if an actor is followed by the default site account. This should replace the old `isFollowing` helper function that reads from the old KV store.
Affected areas:
- Search results to indicate if a search result account is followed by the
default site account
- Profile result to indicate if a profile is followed by the default
site account
- Follows result to indicate if a profile follow result is followed by the
default site account
- `Create` handler when checking if an item should be added to the inbox
- `Announce` handler when checking if an item should be added to the inbox
- `AnnouncedCreate` handler when checking if an item should processed
This change also ensures that `site` on the `AppContext` is typed …

Updated application to use `isFollowedByDefaultSiteAccount`

---

src/http/api/accounts.ts

ref https://linear.app/ghost/issue/AP-690
Pretty much whenever we return external accounts we need to know whether or not we're following them so that we can correctly render follow/unfollow buttons

Added missing isFollowing property to follows API

---

src/dispatchers.ts

refs [AP-698](https://linear.app/ghost/issue/AP-698/announced-activities-not-showing-up-in-the-inbox-feed)
When persisting `Announce` objects we sometimes don't persist the object being announced ON the activity itself. This breaks any queries that rely on the `object` field of the `Announce` activity (i.e retrieving activities). This fix ensures that the object being announced is always persisted on the `Announce` activity

Fixed persisting of `Announce` activities

---

features/site-data.feature
features/step_definitions/stepdefs.js
src/app.ts
src/handlers.ts

We don't want site data to be read by anyone but the site itself. This also cleans up an old console log in the site data handler.

Required Owner role to read site data

---

features/repost-activity.feature
features/step_definitions/stepdefs.js
src/app.ts
src/dispatchers.ts
src/handlers.ts

ref https://linear.app/ghost/issue/AP-702
- added `POST /actions/reposts/:id endpoint` to create a Repost
- a Repost is the equivalent of the "Announce" activity in the ActivityPub vocabulary, or "Boost" in the Mastodon vocabulary

Added API endpoint to repost a post

---

features/repost-activity.feature
features/step_definitions/stepdefs.js
src/app.ts
src/handlers.ts

ref https://linear.app/ghost/issue/AP-707
- when undoing a Repost, we:
- create a new Undo activity containing the corresponding Repost/Announce activity to undo
- send the Undo activity to all followers of the acting user
- remove the original Announce from the database
- remove the Announce item from the user's outbox
- remove the Announce item from the user's reposted collection

Added endpoint to undo a Repost

---

src/account/account.service.integration.test.ts
src/account/account.service.ts
src/account/types.ts
src/helpers/ghost.ts
src/site/site.service.ts

Ref https://linear.app/ghost/issue/AP-737/
- While creating an account we used the default name, icon and bio
- This change will use the site settings to fetch the name, icon and bio while creating the AP account and we'll use the default ones only if the info is missing in site setting.

Update account data using site info while creating internal account

---

src/account/account.service.integration.test.ts
src/account/account.service.ts
src/app.ts
src/constants.ts
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts
src/feed/feeds-updated.event.ts
src/post/post-created.event.ts
src/post/post.entity.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

refs [AP-753](https://linear.app/ghost/issue/AP-753/handle-adding-a-post-to-a-feed)
Implemented adding a post to a feed using the application event bus: When a post is created, a `post.created` event is emitted which gets picked up by the `FeedService`. The `FeedService` will then handle this event and add a post to the appropriate feed(s) based on the audience of the post

Implemented adding a post to a feed

---

src/app.ts
src/dispatchers.ts
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts

refs [AP-719](https://linear.app/ghost/issue/AP-719/add-to-posts-feeds-reposts-table-when-announce-inbox-handler-is)
When the `Announce` handler is executed we now add the reposted post to the `posts` table as well as inserting into the correct user feeds in the `feeds` tables

Added reposted post to post & feeds table when announce handler executed

---

src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts
src/post/post.entity.ts
src/post/post.repository.knex.ts

no refs
Changes include:
- Bailing early if there are no reposts - This is required to prevent an unhandled error (passing empty array to query)
- Bailing early if no feeds where updated - Same as above
- Moved `feed.updated` event emission in to the event handler to keep related event logic together
- Only emit `feed.updated` event if a user's feed was actually updated 
- Refactored feed service test:
- Added helpers for common operations across tests
- Renamed account variables to better reflect what they are

Misc feed service updates

---

migrate/migrations/000011_add-unique-constraint-to-feeds.down.sql
migrate/migrations/000011_add-unique-constraint-to-feeds.up.sql
src/feed/feed.service.ts

closes https://linear.app/ghost/issue/AP-765
We don't want to allow for multiple entries of the same item in the feeds table
so we have added a UNIQUE constraint. It needs to include the `reposted_by_id`
because the same post can be in the feed multiple times due to reposts.
With the new UNIQUE constraint on the feeds table, we need to make sure we
handle conflicts when inserting. The `batchInsert` method in knex is just a for
loop like this, but doesn't allow using the `onConflict` method. We've pulled
that out and ensured everything is still run inside of a transaction

Added UNIQUE constaint to feeds

---

src/account/account.service.ts
src/dispatchers.ts
src/handlers.ts
src/post/post.service.ts

closes https://linear.app/ghost/issue/AP-774
closes https://linear.app/ghost/issue/AP-771
We were incorrectly throwing a URL instead of an Error when the Actor wasn't found. This has been fixed, as well as the error message improved so that we can see exactly what the problem was.
We were throwing when recieving invalid posts, but this is not an error, it's an expected path - so instead we're returning null. We've also improved the error message for when the post isn't found at all.

Improved error handling for getByApId methods

---

.github/workflows/build.yml
yarn.lock

We want to make sure that we don't add changes to the package.json which are not reflected correctly in the yarn.lock file.

Checked yarn.lock integrity during CI

---

src/app.ts
src/handlers.ts

For outgoing likes, we want to store the like in our `likes` table immediately,
this is so that we can track the likes of posts outside of our system, as well
as not relying on the incoming activity to store likes for posts inside out
system. This will allow us to eventually optimise and not send outgoing
activities to ourself, instead updating state immediately, as we do here.

Wired up like action to the new db tables

---

src/app.ts
src/handlers.ts
src/post/post-dereposted.event.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

Ref https://linear.app/ghost/issue/AP-733/remove-from-reposts-table-when-derepost-api-action-is-executed

Wired up derepost action to the new db tables

---

src/http/api/account.ts
src/http/api/feed.ts
src/http/api/helpers/post.ts
src/http/api/search.ts
src/http/api/types.ts

The types Post and Account share a name with the Post&Account entities and this can cause confusion. Being specific about makes them easier to work with.

Renamed types to be more specific

---

src/post/post.entity.ts

Due to how we defined the `url` property in the constructor, instantiated Post entities had a nullable url property, but this is not possible. I've fixed the constructor here to make sure that the type is always URL.

Fixed the Post entity url type

---

src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/account/account.repository.knex.ts
src/feed/feed-update.service.unit.test.ts
src/http/api/feed.unit.test.ts
src/post/post.entity.unit.test.ts
src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/AP-723
ref https://linear.app/ghost/issue/AP-722
In order to create an AccountDTO from an Account entity, we need a `url` property, and the `url` property depends on `apId` as a fallback. We've implemented this in the same way as the Post entity.

Added url and apId to Account entity

---

migrate/migrations/000013_remove-duplicate-articles.down.sql
migrate/migrations/000013_remove-duplicate-articles.up.sql
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.repository.knex.integration.test.ts

closes https://linear.app/ghost/issue/AP-790
closes https://linear.app/ghost/issue/AP-791
We were creating the post without using the `uuid` which resulted in the
incorrect ActivityPub ID being generated, and us creating duplicate entries.
This has been fixed by using the `uuid` given to us by ghost, so we have
consistent ids throughout the system.
Now that we've fixed newly created articles we want to clean up the old ones.
The rows that have a missing `excerpt` are the ones which have the correct
`uuid` so we want to retain these rows, and copy over the missing excerpt.
First we mark all of the rows _without_ a missing excerpt with a `type` of 3,
this is currently unused in the system and we use it as a mark to delete them.
Then we copy the excerpt from posts with an excerpt to ones …

Fixed duplicate articles in Inbox

---

src/http/api/webhook.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.repository.knex.integration.test.ts
src/publishing/content.ts

We were storing posts without cleaning their html first, which meant we were
storing the wrong content, as that was not what is in the activity.
The cleaning of content is business logic and so belong in the entity. Whilst
the publishing is not hooked up to the entity we've had to duplicate this logic
for now, but eventually ti will be removed from the publishing service, which
will hook into our events to create an Article when the post is persisted.

Added content cleaning to Post

---

src/http/api/types.ts

This makes writing serialisers slightly easier as we can refer to the AuthorDTO type in a function that will serialise accounts for both the author and the repostedBy properties.

Exported AuthorDTO type

---

features/delete-post.feature
features/step_definitions/stepdefs.js
src/app.ts
src/http/api/index.ts
src/http/api/post.ts

refs [AP-810](https://linear.app/ghost/issue/AP-810/unblock-frontend-work-with-a-mock-deleteid-http-api)
Added a dummy delete post API endpoint that returns a 204 response for the purpose of enabling the frontend to simulate a delete post action. This logic to be implemented in this endpoint will be fleshed out at a later time

Added dummy delete post API endpoint

---

src/post/post-deleted.event.ts

refs [AP-811](https://linear.app/ghost/issue/AP-811/decouple-backend-work-with-a-shared-postdeletedevent)
Added `post.deleted` event that can be used to notify services that a post has been deleted

Added `post.deleted` event

---

src/account/account.entity.ts
src/handlers.ts
src/http/api/note.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts

ref https://linear.app/ghost/issue/AP-812
We've kept the `deleted` property private for now, and expose access via a static `isDeleted` method on the class. The idea here is that the soft deletition is an implementation detail which we're not sure we want to leak to consumers right now.
When a Post is deleted, we make sure that none of the content is available from the entity - this means we can be sure that we never serve deleted content to the client. Generally we shouldn't be dealing with instances of deleted entities - but there are a few cases we might:
1. When we've just called `delete` on it
2. When we're working with reply threads and a post in the chain is deleted, we may want to indicate that there _was_ a parent, case a Tombstone post with no content gives us the flexibility to …

Added delete method to Post entity

---

src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/AP-812
We need to mark deleted posts as deleted in the DB, as well as emit a PostDeletedEvent so that other systems can react to it, for example removing the post from the feed after a deletion.
Newly created posts that are immediately deleted are not a use-case we have and it's not clear on how that should work, this implementation simply does not persist them for now, but we can change that in future if we need to support this.
When a post is deleted, the only column we write to is the deleted_at column, this ensures that the content is still available for audit, debug, undoing etc...
We also have to add a new check that the Post author Account has an id property, I would like to move this constraint to the entity layer, but that is outside the scope …

Support persistence of deleted posts

---

src/account/account.entity.ts
src/account/account.repository.knex.ts
src/http/api/helpers/post.unit.test.ts
src/post/post.entity.unit.test.ts

The Site object has the webhook_secret on it which is not necessary for accounts to have access to and poses a security concern if we're passing it about.

Updated Account entity to use AccountSite instead of Site

---

features/step_definitions/stepdefs.js
features/thread.feature
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

refs [AP-801](https://linear.app/ghost/issue/AP-801/handle-reading-deleted-posts)
Added handling for reading deleted posts:
- When a deleted post is retrieved from the db, we set its type to `Tombstone`
- When we serialise a post with type `Tombstone` we remove the posts content so we are not leaking deleted post data
- When returning a thread we don't return deleted children

Handle reading deleted posts

---

src/handlers.ts
src/helpers/activitypub/activity.ts
src/http/api/activities.ts

no refs
Improved notifications perf by:
- Making queries for counts optional (not needed for notifications)
- Removing queries for likes & reposts when retrieving activities (not needed for notifications)
- Only doing lookups for likes & reposts when data is provided (not needed for notifications)

Misc notification perf improvements

---

features/create-note.feature
features/create-reply.feature
features/delete-post.feature
features/feed.feature
features/follow-account.feature
features/handle-announce.feature
features/handle-create-article.feature
features/handle-group-announce.feature
features/like-activity.feature
features/repost-activity.feature
features/step_definitions/stepdefs.js
features/thread.feature

Rather than manually doing the whole follow dance between us/actors we can make the tests more readable by combining these into one step.

Simplified setting up follow relations in cucumber tests

---

package.json

This command resets the local state so we can test the empty states easier, we wipe the database and then restart the services. The only thing needed to do is to restart Ghost which we can't easily do from here so has to be done manually

Added wipe-db command

---

migrate/migrations/000020_add_generated_columns_and_indexes_to_key_value.down.sql
migrate/migrations/000020_add_generated_columns_and_indexes_to_key_value.up.sql

closes https://linear.app/ghost/issue/AP-844
- Changed the generated columns to truncate the ids. The old code had '', which caused rows on the left and right join to match and return data that it wasn't supposed.

Fixed database generated columns and indexes

---

src/account/account.repository.knex.integration.test.ts
src/account/account.repository.knex.ts
src/account/account.service.integration.test.ts
src/account/account.service.ts
src/app.ts
src/core/events.ts
src/feed/feed.service.integration.test.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts
src/site/site.service.integration.test.ts
src/site/site.service.ts

ref https://linear.app/ghost/issue/AP-859
We don't want to run the event handlers outside the scope of a request, because the container can be shut down once the request has finished executing. This change keeps our event handlers running within the lifetime of the request.
Long term this will be handled by using a queue for the domain event system, so they can be pushed outside of the request lifecycle and safely handled async

Updated repository to wait for events to process

---

migrate/migrations/000021_remove-likes-of-deleted-posts.down.sql
migrate/migrations/000021_remove-likes-of-deleted-posts.up.sql
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/AP-864
When posts are deleted their likes are kept in the `likes` table, which means that we fetch deleted posts when looking up a users liked posts as well as we counts including likes for deleted posts.
In order to get liked posts for a user which don't include the deleted ones we need to filter on the joined posts table - which is inefficient.
This also includes a migration to remove existing likes for deleted posts. This migration is not reversible.

Removed likes from deleted posts

---

.github/workflows/build.yml
src/app.ts

We move the `/mq` endpoint a lot earlier in the HTTP stack so we skip unnecessary middleware like auth.
We also add a new `MANUALLY_START_QUEUE` option for the env, when this is set we will force Fedify to start the queue when the application boots.
The `startQueue` method requires that we pass a valid `ContextData` to it, and we've had to pass a KV store scoped to `"UNUSED_HOST"` in this case. However this store is never used, due to the `ensureCorrectContext` function which wraps all `fedify` handlers. 
This function will override the `db` property on the context data, scoping the store to the `host`. This `host` is captured in the message on the queue and will be set by Fedify on the context

Enabled ActivityPub to be run as just a MessageQueue handler

---

docker-compose.yml
pubsub/start.sh

ref https://linear.app/ghost/issue/AP-880
We want to set up a second topic to separate the Ghost & Fedify messages at the infrastructure level, this avoids awkward routing code at the application level and decouples the internal events from Fedify related implementation code.

Configured local PubSub to have two topics

---

src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/AP-880
When sending messages on PubSub we want to keep size to a minimum, to achieve this we'll use id's instead of values and then fetch the values from the DB.

Added getById method to KnexPostRepository

---

.github/workflows/build.yml

ref no-issue
- This is a regression introduced that tagged edge and main on every PR. This changes back to only tagging those values on the main branch.

Fixed container tags in branches other than main

---

features/notifications.feature
src/app.ts
src/http/api/index.ts
src/http/api/notification.ts
src/http/api/types.ts
src/notification/notification.service.ts

refs https://linear.app/ghost/issue/AP-899
Added a new endpoint for retrieving notifications with a dummy implementation:
- Adds a new `GET /notifications` endpoint
- Adds a new `NotificationService` that will be responsible for fetching notifications from the database
- Service follows the same pattern as the `FeedService`
- In the future this service may also be responsible for inserting new notifications into the database

Added wire-up for new notifications endpoint

---

features/step_definitions/stepdefs.js
src/account/account.service.integration.test.ts
src/account/account.service.ts
src/constants.ts
src/feed/feed.service.integration.test.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts
src/site/site.service.integration.test.ts

no refs
We decided to remove the usage of table constants in favour of string literals. This brings constistency where table names are referenced and also makes writing / reading complex queries easier

Remove table const usage in favour of string literals

---

src/app.ts

ref https://linear.app/ghost/issue/AP-871
As part of our debugging efforts with the followers collection sync issues, we want to temporarily log out the response body of our followers collection requests to get an idea of what's being returned.

Added logging of followers collection response

---

src/app.ts

ref https://linear.app/ghost/issue/AP-973
We don't update the /site endpoint as this is used for the handshake exposesthe webhook secret. There's no need for Administrators to have access to this.

Permit Administrators to use the API

---

src/helpers/activitypub/actor.ts
src/helpers/activitypub/actor.unit.test.ts

Currently, searching for `@bsky.brid.gy@bsky.brid.gy` in Ghost yields no results. 
Reason is that [the regex check for handle](https://github.com/TryGhost/ActivityPub/blob/main/src/helpers/activitypub/actor.ts#L92) is failing because it doesn't account for dots (.) in the username part. The current pattern [\w-] only allows word characters (a-z, A-Z, 0-9, _) and hyphens (-).
- Changed `[\w-]` to `[\w.-]` in the first capture group to allow dots in usernames
- This will now match handles like `@bsky.brid.gy@bsky.brid.gy`

Account for dots (.) in the username part of handle

---

src/account/account-followed.event.ts
src/account/account.service.integration.test.ts
src/account/account.service.ts
src/app.ts
src/notification/notification-event.service.ts
src/notification/notification-event.service.unit.test.ts
src/notification/notification.service.integration.test.ts
src/notification/notification.service.ts

ref https://linear.app/ghost/issue/AP-901
Update the system to emit a `account.followed` event when an account is followed. This event is then picked up by the `NotificationEventService` which will insert a notification into the database for the account being followed.

Added notification for an account being followed

---

src/post/post-liked.event.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/AP-901
Emit `post.liked` event when a post is liked so that we can listen on this event and create a corresponding notification for the post author.

Emit `post.liked` event when a post is liked

---

src/notification/notification-event.service.ts
src/notification/notification-event.service.unit.test.ts
src/notification/notification.service.integration.test.ts
src/notification/notification.service.ts

ref https://linear.app/ghost/issue/AP-901
Updated the system to handle a `post.liked` event when a post is liked - The event gets picked up by the `NotificationEventService` which will insert a notification into the database for the author of the post being liked.

Added notification for a post being liked

---

features/feed.feature
features/profile-posts.feature
features/step_definitions/stepdefs.js
package.json
yarn.lock

Ref https://linear.app/ghost/issue/AP-1003
Ref https://linear.app/ghost/issue/AP-947
- We added this because the tests were fast enough to create two or more notes in the same second which made it impossible to test features like pagination, order when results were ordered by a timestamp column
- Not required anymore as we are using precision of 6 for all our db columns.

Removed fake timer from cucumber tests

---

src/app.ts

ref https://linear.app/ghost/issue/AP-1005
ref https://linear.app/ghost/issue/AP-964
- we've recently enabled ActivityPub for Admin users
- Admin access was missing for the new /notifications and /post/:post_ap_id endpoints

Enabled /notifications and /post/:post_ap_id endpoints for Admin users

---

.github/workflows/build.yml

ref https://linear.app/ghost/issue/AP-1008
- Staging resource names changed. CD has to reflect those name changes.

Changed staging CD

---

src/app.ts
src/mq/gcloud-pubsub-push/mq.ts

ref no-issue
- On an API deployment, we don't need to check if there's a valid PubSub
subscription, only on queue processing deployments.

Changed subscription checks

---

src/app.ts

ref https://linear.app/ghost/issue/AP-1013
- We're currently sending production as environment for all Sentry exceptions. We need to send either staging or production.

Send sentry environment

---

.github/workflows/build.yml

closes https://linear.app/ghost/issue/AP-1014
- To better debug some issues, it's useful to set the PR number and git sha as docker tags.

Updated GCP registry tags

---

src/app.ts
src/http/api/profile.ts

ref https://linear.app/ghost/issue/AP-1018
Changed `handleGetProfilePosts` to retrieve repost & reply counts for a post in the outbox from the `posts` table instead of computing the counts based on the data in the `key_value` table. This should make retrieving posts for a remote account more peformant.

Improved `handleGetProfilePosts` perf

---

CONTRIBUTING.md
src/app.ts
src/http/api/post.ts
src/http/api/post.unit.test.ts

ref https://linear.app/ghost/issue/AP-1015
The PostService implements remote fetching, and stores the post locally for us.
Generally we should try to use the service layer in controllers, so we can take advantage of the advanced functionality, as well as the ability to alter the functionality without modifying the repository layer.

Updated the GET /post API to fetch remote posts

---

src/post/post.entity.unit.test.ts

ref https://linear.app/ghost/issue/AP-923
In order to turn URLs into links, we need to be able to test that we do so! This adds some tests for the existing functionality of createNote so that we can build on it later.

Added some unit tests for createNote

---

src/db.ts
src/http/api/profile.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/AP-1022
When computing liked / reposted status on posts retrieved for a remote account, we now use the database instead of the key value store for better efficiency and to move away from using the key value store as a source of this information

Updated logic for computing liked / reposted status on remote account post retrieval 

---

package.json
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/publishing/content.ts
src/publishing/content.unit.test.ts
src/publishing/service.ts
src/publishing/service.unit.test.ts
yarn.lock

closes https://linear.app/ghost/issue/AP-923
When we create notes and replies we want any URL's to be clickable links for clients, both in Ghost and in third party services like mastodon. In order to ensure this we convert the URL to an anchor tag, which is then used both internally in Ghost & sent as the content over the ActivityPub network.

Converted URLs in Notes to links

---

.github/renovate.json

NOTE: Preparing changes ready to merge tomorrow when there's been some time for all team members to dissent
---
- The default profile has no automerging, this was chosen originally due to a lack of tests/confidence in CI catching issues with dependency upgrades
- Now we're further along in the project we have confidence to enable automerging
- This will make renovate work for us, keeping packages up to date, instead of creating lots of PRs for us to merge
- Note: The packages @fedify/fedify and @fedify/fedify-cli are excluded from automerge, as requested by @allouis

Updated renovate config to use automerge profile

---

src/account/account.service.integration.test.ts
src/account/account.service.ts
src/account/types.ts
src/constants.ts
src/helpers/activitypub/actor.ts
src/helpers/ghost.ts
src/helpers/ghost.unit.test.ts
src/helpers/user.ts
src/helpers/user.unit.test.ts
src/site/site.service.ts

ref https://linear.app/ghost/issue/AP-1021
- previously, we used:
- `"Local Ghost site"` as fallback for the profile name if not site title was available
- `"This is a summary"` as fallback for the profile bio if no site description was available
-  the Ghost 16x16 favicon as fallback for the profile icon/avatar if no site logo was available
- now, we use:
- a normalized domain name as fallback for the profile name, e.g. `mysite.com`
- no fallback for description (`null`)
- no fallback for icon/avatar (`null`)

Removed fallbacks for account bio & icon, improved fallback for name

---

src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/AP-1011
We currently have a unique constraint on the `ap_id_hash` column in the `posts` table which means that we cannot insert multiple posts with the same `ap_id`. We want this protection, but when there is concurrency in the system, there is a chance that multiple activity handlers are executed at the same time for the same activity resulting in multiple attemps to insert the same post. We want to handle this so that all the activity handlers can execute successfully and finish processing the activity even if the post already exists

Added handling for inserting multiple posts with the same `ap_id`

---

src/post/post.entity.ts
src/publishing/content.ts
src/publishing/content.unit.test.ts

ref https://linear.app/ghost/issue/AP-961
When we do `if (content === post.html) content = ''` we're secretly doing the
removal of member content, for the case where the whole post is member content.
When adding extra steps to the content preparation we may do other
modifications to the content which should not be done if the post
is members only.
Instead the method to remove members content will now remove everything if a
members content marker isn't found. This means that it should never be called
on a public post, this is covered by unit tests in our Post entity.

Handled missing member content marker in ContentPreparer

---

src/http/api/account.ts
src/post/post.service.ts

Ref https://linear.app/ghost/issue/AP-1024/
Previously, this query (`getPostsByAccount`) was used to fetch only the posts of the current user for the Profile view, so `likedByMe` and `repostedByMe` indicated whether the posts were liked or reposted by that account. Now, this query will also fetch posts from other ghost accounts, so the `likedByMe` and `repostedByMe` fields should indicate whether the current user (the one viewing the profile) has liked or reposted the posts.

Updated `getPostsByAccount` query to check if a post id liked/reposted by the current user

---

.github/workflows/build.yml

ref https://linear.app/ghost/issue/AP-1053
We have had a few cases now where the build or deploy has failed on `main` and
we've had no idea until we've manually checked. This should reduce the length
of that loop and allow engineers to fix `main` as and when errors occur

Added notifications for slack

---

src/activitypub/activity.unit.test.ts

ref https://linear.app/ghost/issue/AP-1053
As part of the testing of the slack notification for ci failure we added a breaking test to `main`. This is the cleanup of the broken test.

Fixed breaking test on `main`

---

src/post/content.ts
src/post/post.entity.unit.test.ts

ref https://linear.app/ghost/issue/AP-1054
The linkify-html library was parsing `@user@domain` as an email and converting it into an achore tag with a mail-to attribute. We only want to convert links so we now pass a validation function which only allows the transform of URLs

Fixed ActivityPub handles being turned into mailto links

---

migrate/migrations/000038_remove-duplicate-account-rows.down.sql
migrate/migrations/000038_remove-duplicate-account-rows.up.sql
src/account/account.service.integration.test.ts
src/account/account.service.ts
src/post/post.repository.knex.ts

This is a pretty gnarly migration and has taken a few days to piece together.
We have duplicate (by ap_id) rows in the `accounts` table, which this migration
will clean up completely.
First we create a temporary table `account_masters` which serves as a mapping
between each ap_id and its "master" account, the account that we want to keep.
We populate this initially with internal accounts, using an inner join we only
get ap_ids which have a corresponding row in the users table.
After this we create a list of the remaining ap_ids, and use that to populate
the `account_masters` with the lowest id of each group of ap_ids.
From here we create a temporary table `accounts_to_migrate` which serves as a
mapping between a duplicate account id and its master account id.
Then we update all tables …

Remove duplicate `accounts` rows

---

migrate/migrations/000001_create-key-value-table.up.sql
src/knex.kvstore.ts

ref https://linear.app/ghost/issue/AP-1055
A transaction doesn't help us when the row doesn't exist! Instead we can use
MySQLs ON CONFLICT and then merge the values, effectively doing an upsert.
Knex.js does provide an `upsert` method but this is only implemented for MySQL
and CockroachDB - wheras the onConflict works for SQLite and PostgreSQL, giving
us more portability of the code for an inherently uncertain future.

Fixed error for concurrent writes to key_value

---

src/db.ts
src/db.unit.test.ts

closes https://linear.app/ghost/issue/AP-1069
- Increases connection pool limits. There were timeouts occuring due to connection pool being exhausted.

Increased connection pool limits

---

src/core/result.ts

We want to stop throwing Errors and instead returning Results from our methods in an effor to force us to handle errors explicitly and correctly. This is because we're working in a decentralised system where errors are abundant and expected, and we want to make them first class citizens of our application.
The current state of the system of throwing errors is leading to a lot of 500 errors in production, most of which can and should be handled at the application level, rather than bubbling up.
This implementation is very small and essentially boils down to 2 element tuples containing either null and the value, or an error and null.
A few helper functions have been provided to make the DX a little better, with the idea being that we can either build this up, or replace it with a library …

Added initial Result implementation

---

biome.json
cedar/query-runner/src/app.ts
src/activity-handlers/create.handler.ts
src/app.ts
src/core/events.ts
src/db.ts
src/dispatchers.ts
src/dispatchers.unit.test.ts
src/helpers/activitypub/activity.ts
src/helpers/user.ts
src/helpers/user.unit.test.ts
src/http/api/helpers/account.ts
src/http/api/helpers/account.unit.test.ts
src/http/api/views/account.follows.view.ts
src/kv-helpers.ts
src/lookup-helpers.unit.test.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.repository.knex.ts
src/post/post.service.ts
src/post/post.service.unit.test.ts

We had this set to warning to allow our legacy code to pass lint, but this has result in more uses of explicit any being added to the codebase. The approach here is to add comments to allow the existing cases but ban all new cases.

Banned use of explicit any

---

src/account/account-updated.event.ts
src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/account/account.repository.knex.integration.test.ts
src/account/account.repository.knex.ts
src/activitypub/fediverse-bridge.ts

ref https://linear.app/ghost/issue/AP-1071
These are some building blocks for updating an Accounts profile fields

Migrating modification of Accounts to Entity layer

---

src/activity-handlers/create.handler.ts
src/activity-handlers/delete.handler.ts
src/core/result.ts
src/dispatchers.ts
src/handlers.ts
src/http/api/post.ts
src/http/api/post.unit.test.ts
src/post/post.service.ts

ref https://linear.app/ghost/issue/AP-1045
This uses our new Result type to make sure that we handle all possible errors,
and we no longer return 500's for any of these "expected" errors. If/when we
find that there are still 500's created from this flow, we should explicitly
catch and return these errors and handle them

Updating `getByApId` to return `Result<Post>` 

---

docker-compose.yml
features/account.feature
features/step_definitions/stepdefs.js
src/helpers/activitypub/actor.ts

ref https://linear.app/ghost/issue/AP-963
ref https://github.com/TryGhost/ActivityPub/commit/b68297110e8108676a975fd90bcd9078a72191b2
Our WebFinger implementation validates that the incoming `acct` resource has a
proper hostname, and we require there be a top level domain. In testing our
hostnames were all mapped to docker compose service names and so they do not
have a `.` in them and don't pass this test. This was also the case in the
linked commits `isHandle` function which has a special branch for test mode.
With docker compose we are able to specify aliases for services on a particular
network. I've gone for a separate testing network here to completely isolate
our testing stack, which is probably unecessary, especially because we're using
the `.test` TLD which shouldn't interfere …

Created docker network & configured aliases for tests

---

src/app.ts
src/http/handler/webfinger.ts
src/http/handler/webfinger.unit.test.ts

ref https://linear.app/ghost/issue/AP-963
Removed `custom-webfinger` flag that was being used to validate custom webfinger solution in prod for `www` based hosts

Removed `custom-webfinger` flag

---

features/account-update.feature
features/step_definitions/stepdefs.js
src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/account/account.repository.knex.ts
src/account/account.service.ts
src/account/account.service.unit.test.ts
src/dispatchers.ts
src/dispatchers.unit.test.ts
src/http/api/account.ts

ref https://linear.app/ghost/issue/AP-1076
Implemented the logic needed for updating an account's profile data via the API

Implemented account profile update

---

src/account/utils.ts
src/account/utils.unit.test.ts
src/http/api/views/account.follows.view.integration.test.ts

ref https://linear.app/ghost/issue/AP-963
All of the handles generated by us now no longer have a www. in the host. By updating this util we ensure that handles throughout the application have this www. prefix stripped.
This includes handles external to the our service, which means we may show incorrect handles in the UI for external sites, however we've deemed this to be an edge case for now, and in the case of a bug, it's purely a cosmetic one, those account can still be searched and interacted with using their handle.

Stripped dubdubdub prefix from handles

---

.github/workflows/ephemeral-staging-teardown.yml

ref https://linear.app/ghost/issue/AP-976
- Added closed to the pr check to tear down the staging environment.

Fixed cicd tear down condition to destroy a staging environment

---

src/account/account-updated.event.ts
src/account/account.service.integration.test.ts
src/account/account.service.ts
src/activitypub/fediverse-bridge.ts
src/activitypub/fediverse-bridge.unit.test.ts
src/app.ts
src/http/api/webhook.ts
src/site/site.service.integration.test.ts
src/site/site.service.ts

Ref https://linear.app/ghost/issue/AP-1063/

Removed `site.changed` webhook related code

---

src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/dispatchers.ts
src/handlers.ts
src/helpers/activitypub/actor.ts
src/helpers/activitypub/actor.unit.test.ts

This doesn't clean up all places - we still have a lot of usage that should be cleaned up as we go

Cleaned up usage of 'index'

---

src/account/account-blocked.event.ts
src/feed/feed-update.service.ts
src/feed/feed-update.service.unit.test.ts
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts

Added handling for feed post removal when an account is blocked:
- When an account is blocked remove any posts by the blocked account from the blocking users feed
- When an account is blocked remove any reposts by the blocked account from the blocking users feed

Added handling for feed post removal when account blocked

---

nginx/server.conf

ref https://ghost.slack.com/archives/C06TE92R3JR/p1745461514388069
- by default, nginx has a 1MB limit for client uploads, which is quite low for image uploads
- we are now bumped this limit to 25MB, which is more suitable for image uploads

Fixed image uploads being rejected in local dev with 413 Content Too Large

---

src/http/api/account.ts
src/http/api/views/account.follows.view.integration.test.ts
src/http/api/views/account.follows.view.ts

Ref https://linear.app/ghost/issue/AP-1092
- Used PersistedAccount type for siteDefaultAccount - the current site account cannot be null.
- Used `Result` pattern for fetching follows
- Used `apId` instead of `handle` - same as we have for fetching posts
- If fetching any one follow fails, skipping that so that we can still return the other valid follows in the collection
- Removed getFollowsByApId, the controller now decides if we want to do a local lookup or a remote lookup.
- Modified tests to test getFollowsByAccount and getFollowsByRemoteLookUp separately

AP-1092 | 2 | Added error handling for fetching follows

---

features/create-note.feature
features/create-reply.feature
features/step_definitions/stepdefs.js
src/app.ts
src/handlers.ts
src/http/api/note.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/publishing/service.ts
src/publishing/types.ts
src/storage/gcloud-storage/gcp-storage.service.ts
src/storage/gcloud-storage/gcp-storage.service.unit.test.ts

Ref https://linear.app/ghost/issue/AP-982 https://linear.app/ghost/issue/AP-1084
- Store the image url on the PostEntity in `imageUrl`. This is easier to work with for a single image
- Set the imageUrl on the attachment properties
-- Tested this will many options and setting it to the attachments using Image obj works. By works I mean image correctly shows up on mastodon. 
- Updated /note API to accept an image URL
-- Verifing the image url
- Updated /reply API to accept image
-- Verifing the image url

AP-982 | Attach images to notes/replies

---

src/account/account.repository.knex.integration.test.ts
src/account/account.repository.knex.ts

ref https://linear.app/ghost/issue/AP-1097
When trying to save an account with `null` values for `avatarUrl` or `bannerImageUrl` the underlying db record would not be correctly updated due to the logic for saving the account expecting the provided values to be a URL. `null` is a valid value for these fields so we should handle it accordingly

Added handling for saving an account with `null` values for images

---

src/http/api/views/account.view.ts

The `ap_id` column is not indexed due to the size of it, instead we have the `ap_id_hash` column which contains the SHA256 of the `ap_id` and is indexed. We should never be adding WHERE conditions on the `ap_id` columns in the codebase, it should always be via the indexed hash instead.

Fixed performance of viewByApIdRemote

---

src/app.ts
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts
src/moderation/moderation.service.integration.test.ts
src/moderation/moderation.service.ts
src/post/post.repository.knex.integration.test.ts
src/test/fixtures.ts

Added handling for feed post insertion prevention when an account is blocked:
- When a post is created by a blocked account, ensure it is not put into the feeds of any users that have blocked the author
- When a post is reposted by a blocked account, ensure it is not put into the feeds of any users that have blocked the reposter
- When a post is reposted by an account, ensure it is not put into the feeds of any users that have blocked the author
- When a post is created by a an account and then reposted by a blocked account, ensure it is not put into the feeds of any users except for the reposter

Added handling for feed post insertion prevention 

---

src/http/api/views/account.view.ts

- The `ap_id` column is not indexed due to the size of it, instead we have
the `ap_id_hash` column which contains the SHA256 of the `ap_id` and is indexed. We should never be adding WHERE conditions on the `ap_id` columns in the codebase, it should always be via the indexed hash instead.

Fixed performance of viewByApId

---

src/moderation/moderation.service.ts

Added fix for a flaky moderation service test - The flakiness was being caused due to using the wrong field when returning the list of filtered out users when the author of a post has blocked the reposter. The previously returned field would just happen to match the expected value most of the time, which caused the test to fail intermittently. This fix ensures that the correct field is used to filter out users and prevents the test from failing intermittently.

Fixed flaky moderation service test

---

src/account/account.service.ts
src/http/api/views/account.follows.view.ts

- The `ap_id` column is not indexed due to the size of it, instead we have
the `ap_id_hash` column which contains the SHA256 of the `ap_id` and is indexed. We should never be adding WHERE conditions on the `ap_id` columns in the codebase, it should always be via the indexed hash instead.

Fixed performance of getFollowsByRemoteLookUp and getAccountById

---

src/app.ts
src/moderation/moderation.service.integration.test.ts
src/moderation/moderation.service.ts
src/notification/notification.service.integration.test.ts
src/notification/notification.service.ts
src/test/fixtures.ts

Added handling for notification insertion prevention when an account is blocked:
- When a blocked account has attempted to follow the blocking account, ensure no notifications are not inserted for the blocking account
- When a blocked account has liked a post from the blocking account, ensure no notifications are not inserted for the blocking account
- When a blocked account has reposted a post from the blocking account, ensure no notifications are not inserted for the blocking account
- When a blocked account has replied to a post from the blocking account, ensure no notifications are not inserted for the blocking account

Added handling for notification insertion prevention when an account is blocked

---

src/http/api/__snapshots__/views/AccountView.viewByApId.internal-no-context.json
src/http/api/__snapshots__/views/AccountView.viewById.no-context.json
src/http/api/types.ts
src/http/api/views/account.view.ts

no refs
Removed redundant `attachments` field on account DTO. This was previously added in error as the data that would be stored in this is actually meant for the `customFields` field

Removed redundant `attachments` field on account DTO

---

src/account/account.repository.knex.ts
src/account/account.service.ts

- The `ap_id` column is not indexed due to the size of it, instead we have
the `ap_id_hash` column which contains the SHA256 of the `ap_id` and is indexed. We should never be adding WHERE conditions on the `ap_id` columns in the codebase, it should always be via the indexed hash instead.

Fixed performance of queries using ap_id

---

migrate/migrations/000043_add-following-id-index-to-follows-table.down.sql
migrate/migrations/000043_add-following-id-index-to-follows-table.up.sql

- Added following_id index to follows table. Some queries are using this column on where clauses and will benefit from an index.

Improved performance of queries using following_id

---

migrate/migrations/000044_add-follow-id-index-to-follows-table.down.sql
migrate/migrations/000044_add-follow-id-index-to-follows-table.up.sql

- Added follower_id index to follows table. Some queries are using this column on where clauses and will benefit from an index.

Improved performance of queries using follower_id

---

src/moderation/moderation.service.integration.test.ts
src/moderation/moderation.service.ts
src/notification/notification.service.ts

Added a helper to the moderation service to check if an account can interact with another account. This will be used in various places throughout the application (i.e checking account can follow another account, checking account can like a post by another account etc.). This helper replaces the previously implemented `filterUsersForAccountInteraction` as it was unnecessarily complex for its use case.

Added helper for checking account can interact with another

---

src/activity-handlers/follow.handler.ts
src/app.ts
src/dispatchers.ts

no ref
Moved `follow` handler to dedicated class to follow the same pattern as the `create` & `delete` handlers in preparation for further work re: rejecting follow requests for blocked accounts

Moved `follow` handler to dedicated class

---

src/moderation/moderation.service.integration.test.ts
src/moderation/moderation.service.ts

Removed the logic added for poster filtering from the moderation service as this is now redundant

Removed redundant post filtering from moderation service

---

src/feed/feed.service.ts
src/feed/feed.service.unit.test.ts

ref https://github.com/ghost/ghost/issues/1082
When an account was blocked, the feed items were not being removed from the feed as expected. This was due to a bug where the account id was being used to reference the feed owner instead of the user id associated with the account

Fixed feed items not being removed on block

---

features/step_definitions/stepdefs.js
src/http/api/webhook.ts

ref https://linear.app/ghost/issue/PROD-1572
Ghost sometimes uses a schemaless URL for the profile_image of authors and we weren't able to handle it. This removes the validation entirely and just trusts what Ghost sends.

Allowed invalid URI for authors.profile_image

---

src/account/account.repository.knex.integration.test.ts
src/account/account.repository.knex.ts

When an account blocks another account, any existing follow relationships between both accounts, in any direction, should be removed. This only removes the relationship on our system and does not federate the change (i.e we do not send an `Undo` of the original `Follow` activity).

Ensured follow relationship is removed when account is blocked

---

src/app.ts
src/handlers.ts
src/http/api/follow.ts

no ref
Moved `follow` / `unfollow` API actions to a dedicated controller to follow the same pattern as the `block` controller, in preparation for modification of the `handleFollow` to prevent processing of requests from blocked accounts

Moved `follow` / `unfollow` API actions to dedicated controller

---

src/feed/types.ts

no ref
Removed redundant `PostType` type that was left over from previous feed implementation. This type has been superseded by the `PostType` that is colocated with the `Post` entity → https://github.com/TryGhost/ActivityPub/blob/main/src/post/post.entity.ts#L8-L12

Removed redundant `PostType` type

---

docker-compose.yml
features/step_definitions/block_steps.js
features/step_definitions/stepdefs.js
features/support/db.js
features/support/fixtures.js
features/support/request.js
features/support/steps.js
features/support/utils.js
features/support/wiremock.js
package.json
yarn.lock

no refs
Miscellaneous refactorings to allow us to move to using multiple step definition files instead of one large file:
- Introduced `support` directory to organize support files
- Moved generic helper functions out of `stepdefs.js` and into their respective support files
- Removed nearly all global state from `stepdefs.js`
- Support files keep track of there global state (i.e `db.js` keeping track of database client instance)
- Added `block_steps.js` to organize block related step definitions
- Moved global static constants to environment variables
I opted to just use the built in `World` rather than a custom one - We could maybe move to this at a later point and use it to keep track of global state etc

Refactored cucumber setup to allow for multiple step definition files

---

src/handlers.ts
src/http/api/note.ts
src/http/api/reply.ts

ref https://linear.app/ghost/issue/PROD-669
As part of the block work we're handling specific errors from the API to show a message baout not being able to interact with the account. In order to handle errors easily in the frontend we want to standardise all of the errors returned

Improved error responses from HTTP API

---

src/http/api/like.ts
src/post/post.service.integration.test.ts
src/post/post.service.ts

If an account has blocked another one, and that account attempts to like a post authored by the blocking account via the API, the request will be rejected with a `403`. This is to allow the UI to report this to the blocked user when they attempt to like the blocking account's post

Prevented `like` action from blocked accounts

---

src/http/api/repost.ts
src/post/post.service.integration.test.ts
src/post/post.service.ts

ref https://linear.app/ghost/issue/PROD-669
As part of the block functionality we want to disable interaction entirely for blocked users on our own server. The frontend will display an error when we respond with a 403 indicated that the account has restricted who can interact with them.

Prevented users from reposting content of accounts which have blocked them

---

src/app.ts
src/http/api/search.ts

ref https://linear.app/ghost/issue/PROD-669
We need to be able to show the blocked status in search results, so we have to
include this. Now that we've moved to the AccountView it's as simple as
including it in the type.

Added blockedByMe to search results

---

migrate/migrations/000045_add-domain-to-accounts-table.down.sql
migrate/migrations/000045_add-domain-to-accounts-table.up.sql

ref https://linear.app/ghost/issue/PROD-1637
Added `domain` and `domain_hash` to `accounts` table to optimize the performance of queries that may need to filter accounts by domain (i.e filter ouut all accounts belonging to a specific domain that have been blocked by an account)

Added `domain` and `domain_hash` to `accounts` table

---

package.json
src/http/api/views/account.follows.view.integration.test.ts
src/http/api/views/account.follows.view.ts
yarn.lock

This cleans up the AccountFollowsView a little, improving the test coverage and using the pattern of joins to the `accounts` table for fetching the metadata efficiently.

Preparing AccountFollowsView to add `blockedByMe` flag

---

src/feed/feed-update.service.ts
src/feed/feed-update.service.unit.test.ts
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts
src/feed/feed.service.unit.test.ts

ref https://linear.app/ghost/issue/PROD-669
When a domain is blocked by an account, any feed items (posted or reposted) that they have from accounts that are from the blocked domain are removed

Removed feed items from blocked domain on domain block

---

features/step_definitions/note_steps.js
features/support/utils.js
src/activitypub/fediverse-bridge.ts
src/http/api/note.ts
src/http/api/reply.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.service.integration.test.ts

Ref https://linear.app/ghost/issue/PROD-1569
- For local actors we had image store in `featuredImage` whereas for remote actors it is stored in `attachments` 
- This PR includes changes to store the image in `attachments` when a note/reply is created. 
- `featuredImage` is kept as null - Not required

Storing notes/reply images in post attachments

---

src/account/account-unfollowed.event.ts

ref https://linear.app/ghost/issue/PROD-679
Added `account.unfollowed` event that will later be used to remove feed content from accounts that have been unfollowed

Added `account.unfollowed` event

---

src/feed/feed-update.service.ts
src/feed/feed-update.service.unit.test.ts
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts

ref https://linear.app/ghost/issue/PROD-679
When an account unfollows another account, any posts or reposts from the unfollowed account that appear in the feed of the unfollowing account will be removed. This is so the unfollower does not see content from the unfollowed account in there feed after the unfollow has occurred

Removed posts from feed from unfollowed account

---

src/dispatchers.ts

ref https://linear.app/ghost/issue/PROD-1587
- Added a try/catch to like object network lookup. Previously, it was throwing an error if the remote server was not be reachable.

Fixed error on like object network lookup

---

.github/workflows/cicd.yml
.github/workflows/ephemeral-staging-teardown.yml

ref no-issue
- Fixed a bug where multiple labels would not work on the ephemeral staging routing. It needs to add a route per label (site).

Fixed multiple labels not working on ephemeral staging

---

features/like-activity.feature
src/dispatchers.ts
src/dispatchers.unit.test.ts

ref https://linear.app/ghost/issue/PROD-1734
- the liked collection depends on the key_value store currently
- we decided to drop support for the Liked collection until GA, and then bring it back in context when/if needed
- see https://ghost.slack.com/archives/C06TE92R3JR/p1746692138482949

Returned empty liked collections for actors

---

src/lookup-helpers.ts
src/lookup-helpers.unit.test.ts

Ref https://linear.app/ghost/issue/PROD-1736
- We want to do a Webfinger lookup to validate the handle, and retrieve the actor profile URL: 
- Webfinger lookup  - GET https://domain/.well-known/webfinger?resource=acct:user@domain
- Use the http://webfinger.net/rel/profile-page link if available 
- Otherwise, fallback to self

Added Webfinger lookup for actor profile

---

migrate/gh-ost.Dockerfile
migrate/migrations/000051_alter-key-on-key-value-table.down.sql
migrate/migrations/000051_alter-key-on-key-value-table.up.sql

ref https://linear.app/ghost/issue/PROD-1587
- Key size was preventing some inserts on the key_value table and causing 500 errors.

Increased key column size on key_value table

---

src/constants.ts
src/helpers/activitypub/actor.ts
src/helpers/activitypub/actor.unit.test.ts
src/lookup-helpers.ts
src/lookup-helpers.unit.test.ts
src/post/content.ts
src/post/content.unit.test.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts
src/post/post.service.integration.test.ts
src/post/post.service.ts

Ref https://linear.app/ghost/issue/PROD-1736
- Parse mentions from the Note/Reply content
- If mentions are present, wrap it into hyperlinks and add to the db
- Send a account mentioned event when post is saved with mentions

Added mentions for notes and replies

---

src/app.ts
src/http/api/block.ts
src/http/api/types.ts
src/http/api/views/account.follows.view.integration.test.ts
src/http/api/views/account.follows.view.ts
src/http/api/views/blocks.view.integration.test.ts
src/http/api/views/blocks.view.ts

ref PROD-1636
- Implemented new endpoints to retrieve lists of blocked users and domains
- `/.ghost/activitypub/blocks/accounts` for accounts
- `/.ghost/activitypub/blocks/domains` for domains

Added API endpoints for getting blocked accounts and domains

---

src/account/account-followed.event.ts
src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/account/account.repository.knex.integration.test.ts
src/account/account.repository.knex.ts
src/account/account.service.integration.test.ts
src/account/account.service.ts
src/account/account.service.unit.test.ts
src/activity-handlers/follow.handler.ts
src/dispatchers.ts
src/notification/notification-event.service.ts
src/notification/notification-event.service.unit.test.ts
src/notification/notification.service.integration.test.ts
src/notification/notification.service.ts

ref https://linear.app/ghost/issue/PROD-679
This includes a bunch of modifications to the account system in preparation for usage of the account unfollowed event to remove posts of unfollowed accounts from feeds:
- Emitted `account.unfollowed` event when an account is saved (if applicable)
- Added `follow` & `unfollow` methods to account entity
- Updated account repository to handle persisting of follows based on events
- Updated existing `account.followed` event to use IDs instead of full accounts for consistency with other events
- Added `followAccount` and `unfollowAccount` methods to the account service
- Deprecated usage of `recordAccountFollow` and updated call sites to use `followAccount` instead
- Have marked as deprecated instead of removing completely as the method is still …

Update account system to `follow` / `unfollow` via entity

---

src/account/account.service.integration.test.ts
src/account/account.service.ts

Ref https://linear.app/ghost/issue/PROD-1774/
- We are reading using data.ap_id here instead of the input id because:
- The input id might be the URL of an account (e.g., in the case of mentions).
- In this case, the lookup successfully creates an account, but the actual ActivityPub ID for the account is stored in data.ap_id after mapping.
- If we used the input id directly here, it could lead to a mismatch and fail.

Searching by the actor's id before creating a new account in `ensureByApId`

---

src/account/account.repository.knex.integration.test.ts

Ref https://linear.app/ghost/issue/PROD-1782
- `handles removing rows from the follows table when an account has been unfollowed` test is flaky because database results order is not fixed
- Checking array content with arrayContaining to avoid checking order
- Added length check to ensure correct number of entries in db

Fixed flaky KnexAccountRepository test

---

fake-gcs/start.sh

No ref
- fake-gcs keeps adding .metadata files in storage directory on each server restart
- Added cleanup command to prevent file accumulation in local storage
- Ensures storage remains clean
- This change only affects the local fake-gcs, no changes in the production set-up

Added command to remove accumulating .metadata files in fake-gcs server

---

src/helpers/html.ts
src/helpers/html.unit.test.ts
src/post/content.ts
src/post/content.unit.test.ts
src/post/post.entity.unit.test.ts
src/post/post.service.integration.test.ts

Ref https://linear.app/ghost/issue/PROD-1785/
- In Feed and Profile views, we want to override mention hyperlinks so that the link opens in the Ghost app. 
- Added a `data-profile` attribute to the hyperlink when generating an outgoing Mention
- Frontend can override the default on-click behaviour using this `data-profile` attribute

Added a `data-profile` attribute with the social web handle for mentions

---

src/http/api/views/account.posts.view.integration.test.ts
src/http/api/views/account.posts.view.ts

ref https://linear.app/ghost/issue/PROD-1638
We were incorrectly passing `accountId` instead of `defaultAccountId` to the `mapPostToDTO` method, which resulted in always having true for `authoredByMe`.
This meant that we showed the "delete" button on posts which aren't ours.
I've renamed `defaultAccountId` to `contextAccountId` so it's clearer what it is, added JSDoc to the `mapPostToDTO` method to explain the parameter and fixed which param we pass. I've also fixed the test which should have caught this to expect the correct data.

Fixed `authoredByMe` property when reading local posts

---

src/activity-handlers/follow.handler.ts
src/activitypub/fediverse-bridge.ts
src/activitypub/fediverse-bridge.unit.test.ts
src/http/api/derepost.ts
src/http/api/follow.ts
src/http/api/like.ts
src/http/api/reply.ts
src/http/api/repost.ts

ref https://linear.app/ghost/issue/PROD-1775
When calling `sendActivity` fedify uses the passed username to construct the id of the keypair, which is incorrect, because for existing account the id is always based on the "index" URL. We still only support one account per site, so we can safely hardcode the username which we pass to sendActivity.

Fixed actor & keypair mismatch when sending activities

---

src/activity-handlers/follow.handler.ts
src/activitypub/activity.ts
src/activitypub/activity.unit.test.ts
src/activitypub/fediverse-bridge.ts
src/activitypub/fediverse-bridge.unit.test.ts
src/app.ts
src/dispatchers.ts
src/http/api/derepost.ts
src/http/api/follow.ts
src/http/api/like.ts
src/http/api/reply.ts
src/http/api/repost.ts

ref https://linear.app/ghost/issue/PROD-1775
Our actor dispatcher now correctly uses identifier, so that 'index' is the identifier. We then have a username/handle mapper which is currently hardcoded to 'index'. This allows us to remove a lot of the hardcoding elsewhere in the application, so that we can correctly pass `username`.
Now we're in a good position to move toward multiple accounts, as we will just need to update the `mapHandle` and `actorDispatcher` to correctly fetch from the DB and the `sendActivity` calls will all work as expected.

Updated Actor dispatcher to use identifier

---

src/knex.kvstore.integration.test.ts
src/knex.kvstore.ts

ref https://linear.app/ghost/issue/PROD-685
We want to start cleaning up old keys from the key_value table, for example the idempotency keys created by fedify. The first step toward that is storing the expiry, and then we can run a cron style job to delete expired rows

Support storing expiry in KnexKvStore

---

package.json
src/post/content.ts
src/post/content.unit.test.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.service.ts
yarn.lock

Ref https://linear.app/ghost/issue/PROD-1810/
The updateMentions function handles incoming mentions by:
1. Adding `data-profile` and `rel` attributes to existing mention links
For existing links:
- Preserves the original href and other attributes
- Adds `data-profile` attribute with the mention handle
- Adds `rel="nofollow noopener noreferrer"`
For unwrapped mentions:
- Do Nothing

Incoming Mentions: Added `data-profile` and `rel` attributes to mention links

---

features/5xx-regressions.feature
features/step_definitions/5xx_steps.js
src/app.ts

closes https://linear.app/ghost/issue/PROD-1847
- At the moment AP is throwing 500 instead of 400 when the error Invalid URL is thrown.

Change `Invalid URL` to 400

---

.github/workflows/cicd.yml
docker-compose.yml
jobs/cleanup-expired-key-value-records/Dockerfile
jobs/cleanup-expired-key-value-records/cleanup-expired-key-value-records
package.json

ref https://linear.app/ghost/issue/PROD-685
We can now use `yarn run cleanup-db` to cleanup expired rows from the key_value table locally. This image will also be used as a shceduled CloudRun Job.

Added job for cleaning up key value rows

---

features/create-article-from-post.feature
features/step_definitions/webhook_steps.js
src/http/api/webhook.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.repository.knex.integration.test.ts

closes https://linear.app/ghost/issue/PROD-1843
- At the moment AP is throwing 500 instead of 400 when the error Cannot create Post from private content is thrown.

Change `Cannot create Post from private content` to 400

---

src/helpers/uri.ts
src/helpers/uri.unit.test.ts
src/post/content.ts

No ref
- Added a method that compares two URLs or strings for equality, normalising them by removing trailing slashes

Added `isEqual()` to uri helper

---

.github/workflows/cicd.yml

ref no-issue
- Fixed ci/cd staging tests

Fixed CI/CD staging tests

---

.github/workflows/cicd.yml
.github/workflows/ephemeral-staging-teardown.yml

ref no-issue
- Fixed destroy staging databases when a PR is merged

Fixed destroy tests staging databases when a PR is merged

---

.github/workflows/cicd.yml

ref https://linear.app/ghost/issue/PROD-1662
- Added migrate image to public registry

Added migrate image to public registry

---

src/app.ts

ref https://linear.app/ghost/issue/PROD-1922
When we refactored to use awilix for dependency injection, the next parameter was mistakenly dropped from being passed to the webfinger handler.

Ensured `next` is passed to the webfinger handler

---

src/http/api/views/reply.chain.view.integration.test.ts
src/http/api/views/reply.chain.view.ts

This provides the underlying methods to fetch the paginated data we'll need, but doesn't wire them up to the API yet.
We have the need for paginating on 3 lists:
1. Getting more ancestors, which can be done with the existing `getAncestors` method
2. Getting more children, which we've implemented here with a cursor in the existing query
3. Getting more replies in a chain, which we've implemented here as a new query

Reply chain pagination

---

.github/workflows/cicd.yml

ref https://linear.app/ghost/issue/PROD-1953
- Changed ci/cd to support the second pub/sub topic. Includes deployments to two new services: ghost-queue and fedify-queue.

Changed ci/cd to support second pub/sub topic

---

src/http/api/reply-chain.ts
src/http/api/views/reply.chain.view.ts

ref https://linear.app/ghost/issue/PROD-1945
This just forwards on the `next` param to `getReplyChain` as well as exposes the `next` param based off of the published_at property.

Added support for the `next` param when reading replies

---

src/http/api/views/reply.chain.view.ts

ref https://linear.app/ghost/issue/PROD-1969
The `ap_id` column is not indexed, which means we need to do a full table scan when filtering on it, which kills performance. Instead we have the `ap_id_hash` column for this filter, which is indexed.
Running the original query in production takes ~1s, this one takes ~0.2ms

Filtered on `ap_id_hash` instead of `ap_id`

---

.github/workflows/cicd.yml

This reverts commit 4d43925d3cc572b3666cfc35451adc9a818c6aae.
These topics are not used, and they are failing to deploy, blocking CI.

Removed unused PubSub topic deploys from CI

---

src/post/post-interaction-counts.service.ts
src/post/post-interaction-counts.service.unit.test.ts
src/post/post.entity.ts
src/post/post.repository.knex.ts
src/post/post.service.integration.test.ts
src/post/post.service.ts

ref https://linear.app/ghost/issue/PROD-699
- for remote posts, we want to update interactions counts:
- if they're actively rendered in feeds
- at a lower frequency for older posts
- the update frequency is based on when the post was published:
| Post published            | Refresh interaction counts           |
|----------------------|----------------------------------|
| < 6 hours ago             | At most once every 10 minutes    |
| 6–24 hours ago          | At most once every 2 hours         |
| 1-7 days ago               | At most once every 6 hours         |
| > 7 days ago               | At most once per day                    |

Added logic to trigger interaction count update, when an update is due

---

.github/workflows/cicd.yml

closes https://linear.app/ghost/issue/PROD-2006
When staging deploys fail, we don't continue with prod deploys, so we want to be alerted of them immediately.
The cleanup job is part of our prod infra, we want to be alerted on that too.

Added alerting to failed staging and cleanup deploys

---

src/app.ts
src/pubsub.integration.test.ts
src/pubsub.ts

no ref
Removed explicit pubsub topic / subscription check on app boot as they did not really provide much value (just because topics / subscriptions exist at time of boot doesn't mean they will still exist when we use them) and increased app boot time. If the client tries to publish to a topic that does not exist, an error will be thrown. We currently do not use subscriptions for anything (making the existence check redundant)

Removed explicit pubsub topic / subscription check

---

src/post/post-interaction-counts.service.ts
src/post/post-interaction-counts.service.unit.test.ts
src/post/post.service.integration.test.ts
src/post/post.service.ts

ref https://linear.app/ghost/issue/PROD-699/better-likerepost-counts-in-feedpost-view
- before, when the remote object didn't expose like/repost counts, we would log a misleading "Successfully updated interaction counts for post with ID {postId}"
- now, we instead log "Post with ID {postId} does not expose interaction counts - Skipping"
- also, renamed `postService.update()` to `postService.updateInteractionCounts()` to be more explicit

Added logging when remote post does not expose interaction counts

---

src/http/api/views/reply.chain.view.integration.test.ts
src/http/api/views/reply.chain.view.ts

ref https://linear.app/ghost/issue/PROD-2063
Because posts are soft-deleted in the database we need to explicitly handle them. For children & replies chains we can just act as if they don't exist - but for the ancestors, we need to return a tombstone object instead.

Handled deleted posts in reply chains

---

src/app.ts

no ref
Added Fedify pubsub push endpoint which will eventually replace the existing `/mq` endpoint. This is to standardise the naming of push based subscription endpoints

Added Fedify pubsub push endpoint

---

features/notifications.feature
features/step_definitions/notifications_steps.js
features/support/notifications.js

no-issue
The previous tests were not waiting for the notification to be present before checking for the counts. I've updated the tests to be a little more focused on what we're testing, and pushed some complexity into the step definitions, rather than adding extra steps which verify the notification has been received.
Note that we pass a custom matcher when finding like notifications because matching on the post.id isn't unique enough, as it refers to the post which was liked.

Fixed cucumber tests for notification counts

---

src/app.ts
src/configuration/registrations.ts

no-issue
This doesn't contain any functional changes, it's a copy & paste from app.ts into a function in configuration/registrations.ts
We've wrapped the registrations in a function so we can (in-theory) test it in the future.
We've had to rename a few globals in app.ts to stop the build process from clobbering parameter names.

Refactored DI registrations to separate module

---

docker-compose.yml
nginx/server.conf
src/configuration/registrations.ts

ref https://linear.app/ghost/issue/PROD-2009
This configures nginx so that it can serve our static files from the shared docker volume, and mounts the docker volume so it can be used by the LocalStorageAdapter.
The DI container can conditionally register the LocalStorageAdapter based on the env variables, by default it uses the existing setup.

Allowed LocalStorageAdapter to be configured

---

src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/feed/feed-update.service.unit.test.ts
src/http/api/feed.unit.test.ts
src/http/api/helpers/post.unit.test.ts
src/http/api/post.unit.test.ts
src/http/api/thread.unit.test.ts
src/post/post.entity.unit.test.ts
src/test/account-entity-test-helpers.ts

no-issue
Up until now, we were unable to actually save an AccountDraft because they didn't contain all of the necessary data. This adds the missing data so we can start to wire them up to the repository.

Fleshed out AccountDraft with missing properties

---

package.json
src/mq/gcloud-pubsub-push/mq.ts
src/mq/gcloud-pubsub-push/mq.unit.test.ts
yarn.lock

ref https://linear.app/ghost/issue/PROD-1989
This pre-release of Fedify supports the `nativeRetrial` feature 
for MessageQueue, which we want to enable to allow PubSub to
handle retries. 
This flag tells Fedify not to try and handle retries itself, and will cause the
`handler()` call to error, so we can catch it and notify PubSub that the
message was not processed.

Enabled native retries for the PubSub MessageQueue

---

docker-compose.yml
src/app.ts

no ref
The `/mq` endpoint has been removed in favour of the `/pubsub/fedfiy/push` endpoint that is currently deployed. This change also removes the redundant `MQ_*_SUBSCRIPTION` environment variables that are no longer used

Removed redundant `/mq` endpoint

---

src/post/post.repository.knex.ts

no issue
- This was using the post AP ID instead of the author AP ID
- This bug has been silently there in the codebase
- coderabbitai found this issue in one of my refactoring PRs yesterday. Details [here](https://github.com/TryGhost/ActivityPub/pull/881#discussion_r2154683921)

Fixed author's fallback URL

---

src/dispatchers.ts
src/http/api/feed.ts
src/http/api/feed.unit.test.ts
src/http/api/post.ts
src/http/api/post.unit.test.ts

no issue
- `getDefaultAccountForSite` function returns the old AccountType. We want to reduce the usage of this function

Removed some usage of `getDefaultAccountForSite`

---

src/http/api/views/account.posts.view.ts
src/http/api/views/account.posts.view.unit.test.ts

ref https://linear.app/ghost/issue/PROD-2066/
- `tags` can be an object when there is only one item in tag
- Handled this so that we correctly render mentions in both cases - 1. When tag is array, 2. When tag is an object

Fixed Mentions for Ghost AP user's post

---

src/account/account.service.ts

no-issue
As we move away from the AccountType we don't want to run into a bunch of type errors. These methods only care about an `id` so reducing the types to this make it possible to pass `Account` OR `AccountType`

Fixed dependency on AccountType for params

---

.github/renovate.json5

ref https://linear.app/ghost/issue/PROD-2078
- merging to main ships to production, therefore we want to auto-merge dependency updates only when engineers are online and preferrably earlier in the week

Restricted Renovate auto-merge to Mon/Tue/Wed during working hours

---

features/feed.feature
features/handle-delete.feature
features/step_definitions/feed_steps.js
features/step_definitions/repost_steps.js
features/support/feed.js
features/support/inbox.js
src/app.ts

ref https://linear.app/ghost/issue/PROD-2186
ref https://linear.app/ghost/issue/PROD-2184
We want to rename these concepts in the UI and I'd like to update the API now while we can, so we keep everything in sync.

Added /feed/notes and /feed/reader APIs

---

jobs/backfill-ghost-explore-follows/index.ts

When running this we can overwhelm remote servers so we want to be able to slow down how many requests we're making.

Made delays between batches configurable

---

src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/PROD-2098
We think that the unecessary updates to these columns is causing
contention on the rows, and resulting in slow queries. This solution is
a little bit dirty, pun intended, but a fast way to validate the problem.

Prevented unecessary like & repost count updates

---

src/mq/gcloud-pubsub-push/mq.ts

We're currently experience a lot of load from retrying permanent
failures and we want to stop retrying entirely until we've solved this.

Disabled native retries for PubSub

---

dev/wordpress/README.md
dev/wordpress/start.sh
features/handle-group-announce-create.feature
features/step_definitions/activitypub_steps.js
features/step_definitions/repost_steps.js
src/dispatchers.ts

ref https://linear.app/ghost/issue/PROD-2227
Announced `Create` activities usually come from `Group` actors announcing `Create` activities from members of the group. If you followed the group and not the author account, you would not see the announced posts from the group in your feed (because you are not following the author account and this is checked when adding to the feed). These are now correctly reposted by the group account so they can appear in the feeds of followers of the group
This changeset also includes a dev script for spinning up a local WordPress instance for testing interop

Ensured posts from announced `Create` activities are reposted

---

src/mq/gcloud-pubsub-push/error-utils.ts
src/mq/gcloud-pubsub-push/error-utils.unit.test.ts

ref https://linear.app/ghost/issue/PROD-2210
ref https://github.com/TryGhost/ActivityPub/pull/994
Added handling for non-standard HTTP codes in error analysis - Any error with a non-standard HTTP code will be treated as a permanent failure and will not be retried

Added handling of non-standard HTTP codes in error analysis

---

migrate/migrations/000060_add-account-delivery-backoffs-table.down.sql
migrate/migrations/000060_add-account-delivery-backoffs-table.up.sql

ref https://linear.app/ghost/issue/PROD-2274
Added a new table to track account delivery failure backoffs
- `last_failure_at` & `last_failure_reason` are just for informational purposes
- `backoff_until` & `backoff_seconds` will be used to determine when to retry sending
- `backoff_seconds` doubles on each failure
- `backoff_until` = `NOW()` + `backoff_seconds` after each failure
- When current time < `backoff_until`, we skip sending to the account
- Indexes add on `account_id` & `backoff_until`
- `account_id` for fast lookups on an account
- `backoff_until` for filtering out accounts with backoffs (i.e in followers dispatcher)

Added table to track account delivery failure backoffs

---

src/post/post-updated.event.ts
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/PROD-2287/
- These changes add the post update logic to entity and repository
- `PostUpdateParams` are the fields that can be updated
- A post update even is emitted when a post is updated

Added logic to update a post

---

src/app.ts
src/http/api/webhook.controller.ts

ref https://linear.app/ghost/issue/PROD-2288/
- I have added webhook for post update, delete and unpublish events in the client: https://github.com/TryGhost/Ghost/pull/24333
- Added these dummy APIs so that these urls don't throw errors. 
- I'll build the backend logic for these in upcoming PRs

Added APIs to handle Ghost Post webhook events

---

src/dispatchers.ts
src/mq/gcloud-pubsub-push/error-utils.ts
src/mq/gcloud-pubsub-push/error-utils.unit.test.ts

ref https://linear.app/ghost/issue/PROD-2285
Errors when processing Inbox activitites are surfaced via the inbox error handler, as well as the message queue error handler when running with a queue. This means that for each error in inbox handlers we are reporting to Sentry twice.

Fixed duplicate error reports in Sentry

---

migrate/migrations/000061_add-ghost-ap-post-mappings-table.down.sql
migrate/migrations/000061_add-ghost-ap-post-mappings-table.up.sql

ref https://linear.app/ghost/issue/PROD-2293
- This table will be used to store mapping between ghost post's uuid and AP post ap_id
- Added `ap_id_hash` for faster lookups
- Unique index on `ghost_uuid` and `ap_id_hash`

Added table for ghost uuid to ap post ap_id mapping

---

migrate/migrations/000062_add-inbox-url-hash-to-accounts-table.down.sql
migrate/migrations/000062_add-inbox-url-hash-to-accounts-table.up.sql
src/account/account.repository.knex.ts

ref https://linear.app/ghost/issue/PROD-2266
With the recently added changes around tracking delivery failures, we started reading from `accounts.inbox_url`, but this field was not designed to have lookups done on it so we have added an extra index / hash to improve performance

Added hash / index for account inbox URL

---

src/app.ts

ref no-issue
- CloudRun sends a SIGTERM signal and allows 10 seconds for a container to exit successfully. Sleeping for 9 seconds gives it time to finish processing current requests.

Added graceful termination

---

src/ghost/ghost-post.service.integration.test.ts
src/ghost/ghost-post.service.ts
src/ghost/ghost-post.service.unit.test.ts
src/http/api/webhook.controller.ts

ref https://linear.app/ghost/issue/PROD-2296/
- Added logic to read from the new `ghost_ap_post_mappings` table for updating and deleting posts
- The `ghost_ap_post_mappings` table has been backfilled with data on prod. Commit here: https://github.com/TryGhost/ActivityPub/commit/ba12b87504138343800c79550c697a14d4c97576
- Cleaned up some tests

Added reads from mapping table

---

src/account/account.service.ts
src/mq/gcloud-pubsub-push/mq.ts

The Create activity handler is essentially a noop when handling
activities that we already know about. This means that sending
Create activities to internal accounts is superfluous.

Restricted Create activity sending to external accounts

---

src/mq/gcloud-pubsub-push/mq.ts

ref https://linear.app/ghost/issue/PROD-2324
We have checked that Create activities are not necessary to send and now want to look at other high delivery activities. This is still all gated to fabien.ghost.io whilst we're testing.

Restricted Like, Announce & Delete delivery

---

docker-compose.yml
src/configuration/registrations.ts
src/http/api/site.controller.ts
src/http/api/site.controller.unit.test.ts
src/site/site.service.integration.test.ts
src/site/site.service.ts

ref https://linear.app/ghost/issue/PROD-2284
- context: as we open up the ActivityPub infra to self-hosters, we want to be able to monitor usage
- logic: when a site is created, we check for the request IP address. If the IP address matches one of the Ghost (Pro) IP address, we set the `"ghost_pro"` flag in the `"sites"` table to true

Set Ghost (Pro) flag when creating a new site

---

src/mq/gcloud-pubsub-push/mq.ts

ref https://linear.app/ghost/issue/PROD-2324
The Undo activities also have a large delivery because we send
Undo(Announce) and Undo(Like) to all of our followers.

Restricted Undo activity delivery 

---

src/app.ts

no ref
In dev / test environment we do not need to wait for the graceful shutdown as we want to be able to quickly restart the application when changes are made

Fixed `SIGTERM` handling in dev / test environment

---

src/http/api/site.controller.ts

ref https://linear.app/ghost/issue/PROD-2284
- we have recently added a flag to differentiate Ghost Pro sites, based on the request IP
- currently, it seems we're missing a Ghost (Pro) IP address in our config, and this logging will help us debug the issue

Added logging for the request IP

---

src/mq/gcloud-pubsub-push/error-utils.ts

We are seeing ConnectTimeoutError being thrown in production which we weren't explicitly handling.

Handled ConnectTimeError in error analysis

---

src/http/api/site.controller.ts
src/http/api/site.controller.unit.test.ts

ref https://linear.app/ghost/issue/PROD-2284
- context: as we open up the Ghost (Pro) AP infra to self-hosters, we want to be able to monitor usage
- the previous logic for computing isGhostPro? was flawed: it was looking at the **first** ip address in the `x-forwarded-for` header and matching it against a list of Ghost (Pro) IP addresses. Instead, we want to be matching against the last proxy that forwarded the request to GCP
- new logic: match **any** of the ip addresses in the `x-forwarded-for` header against a list of Ghost (Pro) IP addresses, i.e. evaluate whether the request was made **via** Ghost (Pro)

Fixed "ghost_pro" flag assignment

---

features/step_definitions/5xx_steps.js
features/step_definitions/index.js
features/step_definitions/webhook_steps.js
features/support/content.js
features/support/feed.js
features/support/inbox.js
features/support/notifications.js
src/app.ts
src/http/api/account.controller.ts
src/http/api/block.controller.ts
src/http/api/feed.controller.ts
src/http/api/follow.controller.ts
src/http/api/like.controller.ts
src/http/api/media.controller.ts
src/http/api/notification.controller.ts
src/http/api/post.controller.ts
src/http/api/reply-chain.controller.ts
src/http/api/search.controller.ts

We've migrated to the v1 API now and want to remove these as they should be used anywhere, and it makes it more explicit that filtering on v1 refers to the API exclusively

Removed old API endpoints

---

src/app.ts

ref https://linear.app/ghost/issue/PROD-2331
We want to be able to cache the read-only AP endpoints to help with large spikes of network traffic, e.g. webfingers or actor lookups

Supported Surrogate-Control header for AP endpoints

---

src/account/account.service.integration.test.ts
src/account/account.service.ts
src/account/types.ts
src/feed/feed.service.integration.test.ts
src/helpers/ghost.ts
src/helpers/ghost.unit.test.ts
src/http/api/__snapshots__/views/AccountView.viewByApId.internal-no-context.json
src/http/api/__snapshots__/views/AccountView.viewById.no-context.json
src/http/api/views/account.posts.view.integration.test.ts
src/http/api/views/account.view.integration.test.ts
src/post/post.repository.knex.integration.test.ts
src/site/site.service.integration.test.ts
src/site/site.service.ts
src/test/fixtures.ts

ref https://linear.app/ghost/issue/PROD-2345
When QA'ing the creation of a site we spotted that the cover image for the site was not being imported for the initial profile creation. This changeset fixes this

Fixed `cover_image` retrieval on initial site creation

---

src/app.ts

ref https://linear.app/ghost/issue/PROD-2331
Surrogates like Fastly will not cache requests if they are marked as private, regardless of the Surrogate-Control header.
Marking this as public ensures that the content can be cached by surrogates, and setting a max-age of 0 ensures that browsers don't cache it, giving us full control of purging at the surrogate level.

Ensured that ActivityPub endpoints can be cached

---

src/http/api/views/blocks.view.integration.test.ts
src/http/api/views/blocks.view.ts

ref PROD-2347
- Used existing `getAccountHandle` function for blocked users endpoint
- Added "@" prefix to handles consistently across all user references
- Updated corresponding tests to reflect standardized handle format

Standardized handle format in blocked users list

---

src/mq/gcloud-pubsub-push/mq.ts
src/mq/gcloud-pubsub-push/mq.unit.test.ts

ref https://linear.app/ghost/issue/PROD-2380
When an a message has been retried multiple times, and the error is reportable we should still drop the message, but we shouldn't add a delivery failure for the account as the error is likely on the application side

Updated delivery failure backoff handling for reportable errors

---

package.json
yarn.lock

ref https://github.com/fedify-dev/fedify/pull/352
The `kvCache` wrapper for document loaders was reading straight from the cache, even for preloaded contexts, which mean a large number of DB queries being made for data that is in-memory in the containers.
This patch is a fix for this behaviour which will bypass the cache completely when loading preloaded contexts documents.

Fixed reading preloaded contexts from KvStore

---

.github/renovate.json5
package.json
yarn.lock

`@fedify/cli` was automatically upgraded to `1.8.1` by renovate erroneously
We normally want to upgrade both `fedify` and `@fedify/cli` at the same time to keep them in sync
The renovate config was referencing the incorrect package which meant it auto-merged an unwanted upgrade to `@fedify/cli`

Downgrade @fedify/cli to 1.7.8

---

src/mq/gcloud-pubsub-push/error-utils.ts
src/mq/gcloud-pubsub-push/error-utils.unit.test.ts

We have seen "read ECONNRESET" as well as "connect ECONNRESET" and we want to catch both of them as network connectivitiy errors

Improved handling of ECONNRESET errors

---

biome.json

no ref
Updated biome config schema ref to reference the schema of the installed biome version rather than a static version. This allows us to automatically update biome via renovate without neededing to manually maintain this config

Updated biome config schema ref

---

docker-compose.yml
src/configuration/registrations.ts

no ref
Updated the app to ensure the mysql kvstore is always used. This ensures we don't end up in a split brain situation where production critical data is not split across multiple kvstores

Rollback kvstore changes and ensure mysql is always used for the kvstore

---

src/ghost/ghost-post.service.integration.test.ts
src/ghost/ghost-post.service.ts
src/ghost/ghost-post.service.unit.test.ts

closes https://linear.app/ghost/issue/PROD-2458
- Currently, ActivityPub service listens to the "post.updated" event from Ghost, and if the post does not exist yet in ActivityPub, creates a new post (i.e. it federates it)
- This is unwanted behaviour: it leads to old posts being federated unintentionally

Fixed old posts being federated on update

---

package.json

no issue
- When running `yarn dev` for the first time, new developers run into "Error response from daemon: No such image: activitypub-fake-gcs:latest" and "Error response from daemon: No such image: activitypub-migrate:latest"
- This happens because migrate and fake-gcs are *local* dependencies to the activitypub service

Added predev script to build local dependencies

---

src/app.ts
src/configuration/registrations.ts
src/http/api/account.controller.ts
src/http/api/block.controller.ts
src/http/api/client-config.controller.ts
src/http/api/feed.controller.ts
src/http/api/follow.controller.ts
src/http/api/like.controller.ts
src/http/api/media.controller.ts
src/http/api/notification.controller.ts
src/http/api/post.controller.ts
src/http/api/reply-chain.controller.ts
src/http/api/search.controller.ts
src/http/decorators/route.decorator.ts
src/http/decorators/route.decorator.unit.test.ts
src/http/routing/route-registry.ts
src/http/routing/route-registry.unit.test.ts

ref https://github.com/TryGhost/ActivityPub/pull/1161
ref https://linear.app/ghost/issue/PROD-2441/
- Added two new stable API endpoints:
- client-config (used by the admin)
- notifications/unread/count (used by the admin)
- Updated the route decorators to handle versioning automatically:
- If a request is made to an unsupported API version (e.g. request v1 but only v2 is registered), the response is a 410 with a JSON body containing an error code for "invalid version".
- This will allow the frontend to display a version mismatch message
- Added new route decorator pattern:
- One decorator per endpoint
- If two versions must be supported in parallel, the decorator can take multiple versions as parameters, and the handler can branch internally on `ctx.req.param('version')`

Support dynamic versioning of ActivityPub client

---

src/mq/gcloud-pubsub-push/mq.ts

We didn't have any logs for when we're recording a delivery failure, which leaves us a little blind when debugging. Also updates the log message to use the structured data which is more idiomatic for logtape

Improved logging for delivery backoffs

---

docs/env-vars.md
src/db.ts

ref https://linear.app/ghost/issue/PROD-2530
The connection pool size is generally an infrastructure concern and we want to be able to configure it via the env in terraform.

Made connection pool configurable

---

features/step_definitions/activitypub_steps.js
features/support/request.js
migrate/migrations/000066_add-bluesky-integration-account-handles-table.down.sql
migrate/migrations/000066_add-bluesky-integration-account-handles-table.up.sql
src/app.ts
src/configuration/registrations.ts
src/http/api/bluesky.controller.ts
src/http/api/bluesky.controller.unit.test.ts
src/http/api/helpers/response.ts
src/http/api/types.ts
src/http/api/views/account.view.integration.test.ts
src/http/api/views/account.view.ts
src/integration/bluesky.service.integration.test.ts
src/integration/bluesky.service.ts
src/test/fixtures.ts

ref https://linear.app/ghost/issue/PROD-2410
Added API for enabling / disabling Bluesky for an account:
`POST /.ghost/activitypub/v1/actions/bluesky/enable`:
- Sends follow request to brid.gy account
- Records Bluesky handle for account in the database (upon follow request acceptance)
`POST /.ghost/activitypub/v1/actions/bluesky/disable`
- Sends "stop" DM to brid.gy account
- Sends unfollow to brid.gy account
- Removes Bluesky handle for account from the database
Bluesky handles are stored in a new database table separate from the account table to keep this table free of integration data that may not apply to all accounts ( i.e external accounts)
Bluesky integration status (enabled / handle) is returned when a request is made to `/.ghost/activitypub/v1/account/me`

Added API for Bluesky integration

---

migrate/migrations/000068_increase-image-url-field-size-to-2000.down.sql
migrate/migrations/000068_increase-image-url-field-size-to-2000.up.sql

ref https://linear.app/ghost/issue/PROD-2650
We've seen a couple ER_DATA_TOO_LONG for image urls, which can be up to 2000 characters in the Ghost DB. This brings us in line with Ghost so we avoid these errors.

Updated image_url column size from 1024 -> 2000

---

features/step_definitions/activitypub_steps.js
features/step_definitions/index.js
features/step_definitions/internal_account_steps.js
features/step_definitions/repost_steps.js
features/support/db.js
features/support/feed.js
features/support/request.js

no ref
Bunch of cucumber updates to try and make the test suite less flakey:
- Added missing tables from `Before` and sorted alphabetically
- Removed redundant global `BeforeAll`
- Refactored  `Then the note is in my followers feeds` step to allow for retries to occur in-case there is latency in the system
- Refactored `waitForRequest` to follow same pattern as other `waitFor...` functions to allow for proper exponential backoff
- Refactored `activitypub` steps when checking an activity has been sent to multiple followers in an effort to make these steps more reliable
- Removed unused `Activity {string} is sent to all followers` step

Misc cucumber updates
