TryGhost/ActivityPub

package.json
src/dispatchers.ts
src/user.ts
yarn.lock

This includes the new inbox queue, which means that inbox handlers receive a `Context` instead of `RequestContext`

Updated @fedify/fedify to 0.12.1

---

package.json
src/handlers.ts
yarn.lock

refs [MOM-322](https://linear.app/tryghost/issue/MOM-322/sanitize-html-for-notes-content)
Added sanitization of object content for objects returned by the inbox handler

Santized object content for inbox

---

README.md

Fix off by one error

---

src/dispatchers.ts

The dispatcher for the followers collection is making network calls for each follower which is a waste of resources and time. Instead we will check the local db first for the actor data and if it's not present, we'll fetch over the network and store it for next time.

Used cached Actor data for Followers & Following

---

src/dispatchers.ts

We're running into some performance issues when fetching large followers lists. Ultimately we need to move away from using MySQL as a key value store - but for now we can store the expanded list which should help with performance.

Added expanded followers data to the db

---

docker-compose.yml
features/accept-follows.feature
features/handle-create-article.feature
features/step_definitions/stepdefs.js
package.json
yarn.lock

no-issue
I've added wiremock here as a starting point for allowing us to mock network requests
The cucumber steps have been updated to try and be a little more fluent and reusable.

Improved Cucumber tests and used WireMock

---

src/user.ts
src/user.unit.test.ts

refs [AP-347](https://linear.app/tryghost/issue/AP-347/add-profile-url-to-actor)
Added profile URL to actor so that clients can link to a page that isn't just a JSON blob

Added profile URL to actor

---

docker-compose.yml
features/step_definitions/stepdefs.js
src/app.ts

This is some cleanup that happened during the auth work

Miscellaneous improvements

---

src/handlers.ts
src/helpers/ghost.ts
src/helpers/ghost.unit.test.ts

no refs
Moved the `ghost` helper to `helpers` and updated all references to it

Moved `ghost` helper to `helpers`

---

src/dispatchers.ts
src/handlers.ts
src/helpers/user.ts
src/helpers/user.unit.test.ts

no refs
Moved the user helper to helpers and updated all references to it

Moved `user` helper to `helpers`

---

src/api/action/profile/get.ts
src/api/action/profile/getFollowers.ts
src/api/action/profile/getFollowing.ts
src/api/action/search.ts
src/api/index.ts
src/app.ts

no refs
Added endpoint for retrieving a profie

Added endpoint for retrieving a profie

---

src/api/action/getActivities.ts

refs [TryGhost/Ghost#21254](https://github.com/TryGhost/Ghost/pull/21254)

Add filter for filtering out activities that are replies to other activities

---

src/dispatchers.ts
src/handlers.ts

refs [AP-487](https://linear.app/ghost/issue/AP-487/likes-on-profile-info-displaying-incorrect-actor-info)

Hydrated `attributedTo` in the liked collection

---

src/helpers/sanitize.ts
src/helpers/sanitize.unit.test.ts

ref https://linear.app/ghost/issue/AP-502/make-sanitize-html-keep-the-classes-on-tags

Updated sanitizeHtml rules so we can display Ghost posts properly

---

package.json
yarn.lock

Bumped Fedify to 1.1.1

---

src/helpers/sanitize.ts
src/helpers/sanitize.unit.test.ts

Removed `style` from the allowed tags when sanitizing HTML

---

src/app.ts

ref https://linear.app/ghost/issue/AP-546/add-structured-logging
- we need to output the logs in JSON format so they can be picked up in Cloud Logging and destructured

Fixed structured logging in Cloud Logging env

---

src/api/action/getActivities.ts
src/api/action/profile/get.ts
src/api/action/profile/getFollowers.ts
src/api/action/profile/getFollowing.ts
src/api/action/search.ts
src/app.ts
src/dispatchers.ts
src/dispatchers.unit.test.ts
src/handlers.ts
src/helpers/user.ts
src/helpers/user.unit.test.ts
src/logging.ts
src/lookup-helpers.ts

- we attach this on all request so we can be sure that the metadata that links logs together is present

Switched to request-based logger instance

---

.github/workflows/build.yml
biome.jsonc
features/step_definitions/stepdefs.js
package.json
src/api/action/profile/get.ts
src/api/action/profile/getFollowers.ts
src/api/action/profile/getFollowing.ts
src/api/action/search.ts
src/app.ts
src/db.ts
src/dispatchers.ts
src/dispatchers.unit.test.ts
src/handlers.ts
src/helpers/activitypub/activity.ts
src/helpers/activitypub/activity.unit.test.ts
src/helpers/ghost.unit.test.ts
src/helpers/user.ts
src/knex.kvstore.integration.test.ts
src/lookup-helpers.ts
yarn.lock

ref https://linear.app/ghost/issue/AP-330/add-linting-to-tryghostactivitypub
- this adds Biome to the repo, to do formatting, linting and static analysis of our
code
- right now, linting and formatting are disabled to make the transition
a little easier
- also adds a workflow to run this in CI

Added Biome to repo

---

biome.jsonc
features/step_definitions/stepdefs.js
src/api/action/getActivities.ts
src/api/action/profile/get.ts
src/api/action/profile/getFollowers.ts
src/api/action/profile/getFollowing.ts
src/api/action/search.ts
src/app.ts
src/db.ts
src/dispatchers.ts
src/dispatchers.unit.test.ts
src/example.unit.test.ts
src/handlers.ts
src/helpers/activitypub/activity.ts
src/helpers/activitypub/actor.ts
src/helpers/activitypub/actor.unit.test.ts
src/helpers/ghost.unit.test.ts
src/helpers/user.ts
src/helpers/user.unit.test.ts
src/knex.kvstore.integration.test.ts
src/knex.kvstore.ts
src/kv-helpers.ts
src/kv-helpers.unit.test.ts
src/lookup-helpers.ts

ref https://linear.app/ghost/issue/AP-330/add-linting-to-tryghostactivitypub
- this helps to prevent `any` in the codebase
- also fixed up a few instances I could doref https://linear.app/ghost/issue/AP-330/add-linting-to-tryghostactivitypub
- this helps to prevent `any` in the codebase
- also fixed up a few instances I could do

Enabled noExplicitAny and noImplicitAnyLet lint rules

---

src/constants.ts

Bump pagination page size 10 → 100

---

nginx/server.conf
src/app.ts
src/dispatchers.ts
src/dispatchers.unit.test.ts

refs [AP-485](https://linear.app/ghost/issue/AP-485/add-nodeinfo-endpoint)
Added routing for the `nodeinfo` endpoint

Added `nodeinfo` routing

---

package.json
src/app.ts
yarn.lock

- updates Sentry to the latest version
- also adds `@hono/sentry` as middleware to our app, which should help with deeper integration and better error collection

Improved error collecting via Sentry

---

src/app.ts

ref https://linear.app/ghost/issue/AP-546/add-structured-logging
refs https://logtape.org/manual/contexts#implicit-contexts
- this configures an implicit context for logtape, which allows us to
pass metadata down to the instance used by Fedify
- in this case, it's tracing info used by GCP to link logs + requests
together

Configured implicit contexts for logging

---

src/handlers.ts

no refs
Added handling for when a reply fails to fully send

Added handling for reply failures

---

Dockerfile
package.json
src/app.ts
yarn.lock

- this helps us keep track of which versions are reporting errors

Added K_REVISION to Sentry metadata

---

Dockerfile
package.json
src/app.ts
yarn.lock

This reverts commit ef9671c8558cbe8a017c9a3f0b9fae111f2bb564.

Revert "Enabled Cloud Profiler"

---

src/app.ts

ref https://linear.app/ghost/issue/AP-555/add-requestdb-tracing-to-activitypub
- we don't need 2 middlewares for this

Simplified Sentry setup instrumentation

---

src/api/action/getActivities.ts
src/dispatchers.ts
src/handlers.ts

- we can do more of this at once to avoid waterfalling of DB requests, which is slow

Parallelised all bulk fetches

---

.github/renovate.json

ref https://linear.app/ghost/issue/AP-554/add-renovate-to-the-repository
- this just uses our default config, we might want to tweak it in the future

Added Renovate to repository for dependency management

---

docker-compose.yml
features/sites-restriction.feature
features/step_definitions/stepdefs.js
src/app.ts
src/db.ts

Improve onboarding

---

src/api/action/profile/get.ts

- we have a lot of sequential code in this method that results in a waterfall trace
- this is not efficient, given we can do a lot of it at the same time
- this converts the code to use `Promise.all`, which parallelises a lot of the work here and speeds up the action

Parallelised `profileGetAction` actions

---

src/db.ts

- this reverts commit 59f02e09de264fdd65dac3bdaab0c1d37720263a
- this was not the cause of the memory leak

Re-applied "Increased DB connection pool size""

---

src/instrumentation.ts

- this should no longer be needed

Removed trace filter

---

package.json
yarn.lock

closes https://linear.app/ghost/issue/AP-570
This was wrapped in a try/catch in v1.2.5 of the fedify package.

Fixed uncaught error when body is unusable

---

src/instrumentation.ts

- enabled info logging for OTel, and provides an environment variable which allows us to enable debug logging
- this allows us to see messages from OTel that we may currently be missing

Added logging support for OTel

---

src/instrumentation.ts

- I misread the docs here and didn't realise you shouldn't set up a provider and an SDK separately
- this fixes that by just switching to the SDK

Fixed duplicate initialization of OTel API

---

src/instrumentation.ts

Revert "Fixed duplicate initialization of OTel API"

---

src/instrumentation.ts

- this might help us link together traces using the W3C standard easier

Added W3CTraceContextPropagator to OTel setup

---

src/app.ts
src/mq/gcloud-pubsub-mq.ts

Reverts TryGhost/ActivityPub#181

Revert "Added extra logging to debug mq issue with suspected incorrect context host"

---

src/api/action/getActivities.ts
src/db.ts

Reverts TryGhost/ActivityPub#166

Revert "Fixed `:noReply` filter not filtering replies when retrieving activities"

---

features/create-note.feature
features/step_definitions/stepdefs.js
src/app.ts
src/handlers.ts
src/helpers/activitypub/activity.ts
src/helpers/activitypub/activity.unit.test.ts

refs [AP-610](https://linear.app/ghost/issue/AP-610/create-an-endpoint-for-publishing-notes)
Added a new endpoint to facilitate the creation of a note

Added API endpoint for creating a Note

---

src/api/action/profile/getPosts.ts
src/api/index.ts
src/app.ts

no refs
Added endpoint for retrieving profile posts

Added endpoint for retrieving profile posts

---

src/api/action/profile/get.ts
src/api/action/search.ts
src/helpers/activitypub/actor.ts
src/helpers/activitypub/actor.unit.test.ts

no refs
Misc cleanup after adding profile posts endpoint

Misc cleanup after adding profile posts endpoint

---

src/handlers.ts

closes https://github.com/TryGhost/ActivityPub/issues/50

Added to and cc fields to Articles

---

src/app.ts
src/mq/gcloud-pubsub-push/mq.ts
src/mq/gcloud-pubsub-push/mq.unit.test.ts

no refs
Refactorings include:
- Improved comments on not so obvious code
- Improved usage of logging
- Slight reordering of code for better performance (i.e dont validate data when not needed)
- Consolidation of some input validation
- Naming of anonymous functions

Misc refactoring of the MQ middleware

---

src/api/action/webhook/post-published.ts
src/api/action/webhook/site-changed.ts
src/api/index.ts
src/app.ts
src/handlers.ts

no refs
Moved webhook actions to API for easier maintenance and consistency with other API actions

Moved webhook actions to API

---

src/http/api/activities.ts
src/http/api/webhooks.ts

Clean up API imports after refactor

---

src/http/api/activities.ts
src/http/api/follows.ts
src/http/api/index.ts
src/http/api/posts.ts
src/http/api/profiles.ts
src/http/api/search.ts
src/mq/gcloud-pubsub-push/mq.ts
src/publishing/service.ts

no refs
Refactoring's include:
- Updating API barrel file to export all exports from a module without specifying manually
- Cleaning up JSDoc in the mq module
- Cleaning up the type reference to the hono context in the API handlers

Misc refactoring of comments & types

---

src/http/api/accounts.ts
src/http/api/search.ts
src/http/api/types.ts

no refs
Updated search response to return only the required account data

Updated search response

---

migrate/migrations/000006_add-collections-columns-to-accounts-table.down.sql
migrate/migrations/000006_add-collections-columns-to-accounts-table.up.sql

ref https://linear.app/ghost/issue/AP-656
This was initially missed because we were focused on the data used in the UI to render accounts, but we need this on the backend for the AP interactions.

Added columns to store collections

---

src/site/site.service.ts

ref https://linear.app/ghost/issue/AP-658
This code is not used in production yet, but multiple engineers need to build upon it, so we're pushing it as is, to act as a shared object. Unit tests are required before moving this into prod!

Add initial SiteService

---

features/step_definitions/stepdefs.js
src/app.ts
src/dispatchers.ts

refs [AP-678](https://linear.app/ghost/issue/AP-678/update-incoming-accept-activity-handler-to-record-data-in-the-new)
Updated `Accept` activity handler to record data in the new follows table

Updated `Accept` activity handler to record data in the new follows table

---

src/account/account.service.integration.test.ts
src/account/account.service.ts
src/app.ts
src/dispatchers.ts

refs [AP-662](https://linear.app/ghost/issue/AP-662/update-followers-dispatcher-to-read-data-from-the-new-follows-table)
Updated `followers` dispatcher to read data from the new `follows` table

Updated `followers` dispatcher to read data from the new `follows` table

---

src/app.ts
src/http/api/accounts.ts

refs [AP-665](https://linear.app/ghost/issue/AP-665/update-accounthandlefollowsfollowingorfollowers-endpoint-to-read-data)
Update account follows endpoint ro read data from `follows` table

Update account follows endpoint ro read data from `follows` table

---

src/account/utils.ts
src/account/utils.unit.test.ts
src/app.ts
src/constants.ts
src/feed/feed.service.ts
src/feed/types.ts
src/helpers/activitypub/activity.ts
src/http/api/accounts.ts
src/http/api/feeds.ts
src/http/api/helpers/post.ts
src/http/api/helpers/post.unit.test.ts
src/http/api/index.ts
src/http/api/types.ts

refs [AP-689](https://linear.app/ghost/issue/AP-689/implement-api-endpoint-for-retrieving-a-users-feed)
Implement API endpoint for retrieving a user's feed

Implement API endpoint for retrieving a user's feed

---

features/repost-activity.feature
features/step_definitions/stepdefs.js
src/feed/feed.service.ts
src/handlers.ts
src/helpers/activitypub/activity.ts
src/http/api/activities.ts

Ref: https://linear.app/ghost/issue/AP-703/add-flag-to-activity-to-indicate-it-has-been-reposted-by-the-user
- Added the flag so that UI can indicate that an item in the feed has been shared by the current user

Added flag to activity to indicate it has been reposted by the user

---

features/repost-activity.feature
features/step_definitions/stepdefs.js
src/db.ts
src/helpers/activitypub/activity.ts

Ref https://linear.app/ghost/issue/AP-706

Added query for fetching repost count

---

features/feed.feature
features/step_definitions/stepdefs.js
src/app.ts
src/constants.ts
src/db.ts
src/feed/feed.service.ts
src/http/api/activities.ts
src/http/api/feed.ts
src/http/api/helpers/post.ts
src/http/api/helpers/post.unit.test.ts
src/http/api/types.ts

refs [AP-704](https://linear.app/ghost/issue/AP-704/update-client-to-utilise-new-feed-endpoint-for-inbox-feed-view)
Updated the feed endpoint implementation to handle some edge cases discovered when updating the client to utilise the endpoint

Updated feed endpoint implementation

---

src/account/account.entity.ts
src/account/account.repository.knex.integration.test.ts
src/account/account.repository.knex.ts
src/app.ts
src/core/base.entity.ts
src/core/url.ts
src/http/api/webhook.ts
src/post/post.entity.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

Wire up post published

---

src/app.ts
src/http/api/note.ts
src/post/post.entity.ts
src/post/post.repository.knex.ts

Refs https://linear.app/ghost/issue/AP-717

Added a new note to posts table

---

src/dispatchers.ts
src/dispatchers.unit.test.ts

Ref https://linear.app/ghost/issue/AP-671/clean-up-after-switching-to-using-new-users-accounts-and-follows

Removed unused code related to kv store for followers and following

---

src/handlers.ts

Ref https://linear.app/ghost/issue/AP-671/clean-up-after-switching-to-using-new-users-accounts-and-follows

Removed old code from unfollow handler

---

src/constants.ts
src/post/post-reposted.event.ts
src/post/post.entitiy.unit.test.ts
src/post/post.entity.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

refs [AP-757](https://linear.app/ghost/issue/AP-757/add-the-repost-capability-to-posts)
Implemented repost capability for posts utilising the same pattern as `likes`

Implemented repost capability for posts

---

src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts

refs [AP-758](https://linear.app/ghost/issue/AP-758/handle-adding-a-repost-to-a-feed)
When a post is reposted, it should be added to the relevant feeds. This commit adds the necessary logic to the `FeedService` to handle this

Added handling for adding a repost to a feed

---

src/app.ts
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts
src/handlers.ts
src/http/api/note.ts
src/post/post.entity.ts
src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts
src/post/post.service.ts
src/publishing/service.ts
src/publishing/types.ts

Refs https://linear.app/ghost/issue/AP-716/add-to-posts-table-when-reply-api-action-is-executed

Added to posts table when reply API action is executed

---

src/post/post.entity.unit.test.ts

Pulled shared stuff into a helper, makes for easier reading/writing of tests

Refactored Post entity tests

---

migrate/migrations/000014_remove-replies-in-feed.down.sql
migrate/migrations/000014_remove-replies-in-feed.up.sql

refs [AP-793](https://linear.app/ghost/issue/AP-793/fix-replies-showing-in-the-feed)
Removed replies from the feed via a migration

Removed replies from the feed

---

src/http/api/helpers/post.ts
src/http/api/helpers/post.unit.test.ts

ref https://linear.app/ghost/issue/AP-723
ref https://linear.app/ghost/issue/AP-722
This will be required by both the note and the reply HTTP API's so that they can return the correct response type. Note that we currently use the `apId` as the `id` to follow how the FeedService is implemented, this is to decouple the changes, as other endpoints rely on the id being a URL. Once everything is migrated to use the new DB we can then switch to using uuids here.

Added a Post -> PostDTO serialiser

---

src/feed/feed-update.service.ts
src/feed/feed-update.service.unit.test.ts
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts

refs [AP-802](https://linear.app/ghost/issue/AP-802/remove-deleted-posts-from-feeds)
Implemented removing deleted posts from feeds

Implemented removing deleted posts from feeds

---

src/app.ts
src/dispatchers.ts
src/feed/feed-update.service.ts
src/feed/feed-update.service.unit.test.ts
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts

ref https://linear.app/ghost/issue/AP-813/dereposts-are-not-removed-from-the-feed-and-inbox
- Removes dereposted posts from feed
- Handles derepost when Undo(Announce) activity is received

Dereposted post should be removed from the feed

---

src/http/api/activities.ts

no refs
Improved notifications perf by:
- Removing the outbox from the activities query (not needed for notifications)
- This allows us to sort the inbox activities by position in the list rather than by timestamp, which means we don't need to query for all the timestamps up front
- Pre-slicing the data to fetch to reduce the size of the query
- This could mean that less items than requested are returned, but it means that the query is faster and the client can request more items if needed

More misc notification perf improvements

---

src/http/api/activities.ts

Fixed erroneous count lookups when fetching notifications

---

src/http/api/activities.ts

no refs
Added batching mechanism when building activities to reduce resource exhaustion when building a large number of activities

Added batching to building activities

---

features/feed.feature
features/step_definitions/stepdefs.js
migrate/migrations/000022_add-published-at-to-feeds.down.sql
migrate/migrations/000022_add-published-at-to-feeds.up.sql
src/feed/feed.service.integration.test.ts
src/feed/feed.service.ts
src/post/post.service.ts

Ref https://linear.app/ghost/issue/AP-895/liking-an-old-post-that-is-not-in-the-new-database-causes-it-to-be

Added published_at column to feeds table

---

cedar/README.md
cedar/args.sh
cedar/data-generation/config.js
cedar/data-generation/data-generate.sh
cedar/data-generation/data-reset.sh
cedar/data-generation/package-lock.json
cedar/gcloud.sh
cedar/query-runner/src/app.ts
cedar/setup.sh
cedar/upload-data.sh

ref https://linear.app/ghost/issue/AP-898
I've added some top level scripts for getting a DB up and running with fake data

Added top level scripts for Cedar

---

.github/workflows/build.yml

ref https://linear.app/ghost/issue/AP-896
- Created a new registry with proper naming and security scanning
- Registry is multi-region for faster failover

Added push step to the future main registry

---

migrate/migrations/000025_add-notifications-table-up-down.sql
migrate/migrations/000025_add-notifications-table-up.sql

refs https://linear.app/ghost/issue/AP-897
Added migrations for notifications table

Added migrations for notifications table

---

migrate/bin/up

ref https://linear.app/ghost/issue/AP-921/%5Binfrastructure%5D-cloudrun
- Added another way to run migrate: using private ip connection inside a VPC in GCP
- Removed DB_PASS from log output

Changed migrate to use mysql private ip connection

---

.github/workflows/build.yml
src/db.ts

closes https://linear.app/ghost/issue/AP-896
- Updated CI/CD to deploy main to staging

Updated CI/CD to deploy main to staging

---

src/http/api/notification.ts
src/http/api/types.ts
src/notification/__snapshots__/get-notifications-data.json
src/notification/notification.service.ts

ref https://linear.app/ghost/issue/AP-900
Added post type to notifications response so that the client can display the correct information based on the type of associated post

Added post type to notifications response

---

package.json
yarn.lock

This includes some fixes to the followers collection sync mechanism

Bumped fedify to 1.4.9

---

features/step_definitions/stepdefs.js
jobs/migrate-site-inbox-to-notifications/index.mjs
src/db.integration.test.ts
src/db.ts
src/db.unit.test.ts
src/test/db.ts

Ref https://linear.app/ghost/issue/AP-886/
Ref https://linear.app/ghost/issue/AP-992/

Set timezone to UTC in mysql connection config 

---

src/http/api/notification.ts
src/notification/notification.service.ts

ref https://linear.app/ghost/issue/AP-901
Misc notifications clean up:
- Fixed an incorrect mapping
- Updated / added comments to make code clearer

Misc notifications clean up

---

.github/workflows/build.yml

ref https://linear.app/ghost/issue/AP-896
- Fixed staging CD sql connectio, the connection name was incorrect.

Fixed staging CD sql connection

---

biome.json
package.json
yarn.lock

ref https://linear.app/ghost/issue/AP-871/investigate-loss-of-followers

Disabled Followers Collection Sync

---

.github/workflows/build.yml

ref https://linear.app/ghost/issue/AP-1004
- Added production cicd

Added production cicd

---

.github/workflows/build.yml

ref no-issue
- Removed cicd default labels, they were interering with terraform apply.

Removed cicd default labels

---

.github/workflows/build.yml

ref https://linear.app/ghost/issue/AP-1004
- Removed old infrastructure from cicd, the new resources are already being used.

Removed old infrastructure from cicd

---

src/activitypub/activity.unit.test.ts

ref https://linear.app/ghost/issue/AP-1053
This is to confirm that the slack notifications are working correctly.

Added breaking test to `main`

---

.github/workflows/build.yml

ref no-issue
- CI/CD failed due to service account rename

Fixed cicd

---

features/account-update.feature
features/step_definitions/stepdefs.js
src/account/account.service.ts
src/app.ts
src/http/api/account.ts

Ref https://linear.app/ghost/issue/AP-1076/

Added endpoint for updating an account information

---

.github/workflows/cicd.yml

ref no-issue
- Steps were being skipped on build test push due to if condition

Fixed cicd deploy pipeline

---

src/http/api/account.ts
src/post/post.service.ts

Ref https://linear.app/ghost/issue/AP-1075

Refactored `getPostsByRemoteLookUp` to return the `Result` type

---

migrate/migrations/000040_add-blocks-table.down.sql
migrate/migrations/000040_add-blocks-table.up.sql

Added a database table that will store a record of an account block. We will later query this table to determine if an account has blocked another account / is being blocked by another account.

Added database migrations for `blocks` table

---

package.json
src/moderation/moderation.service.integration.test.ts
src/moderation/moderation.service.ts
src/test/fixtures.ts
yarn.lock

Added moderation service to encapsulate the logic for ensuring content from blocked users is not shown to the blocking account
This also adds a new test fixture manager to simplify the creation of test data for integration tests

Added moderation service

---

src/http/api/views/account.view.integration.test.ts

no refs
When the account view changes were merged we started seeing flaky tests due to timeouts. Looking at the tests, there's not a whole lot that can be optimized to try and reduce the likelihood of timeouts. For this set of tests, we have increased the timeout to 10 seconds, which is a similar approach to we have taken for the integration tests for the feed service

Added increased timeout on integration test for account view

---

migrate/migrations/000041_add-user-id-post-type-index-to-feeds-table.down.sql
migrate/migrations/000041_add-user-id-post-type-index-to-feeds-table.up.sql

ref no-issue
- This should speed up the feeds UI. Slack ref: https://ghost.slack.com/archives/C06TE92R3JR/p1745319537627759

Added index to feeds table

---

src/http/api/account.ts
src/http/api/views/account.follows.view.ts

Ref: https://linear.app/ghost/issue/AP-1092

AP-1092 | 1 | Removed null check on account

---

src/post/post.repository.knex.ts

ref https://linear.app/ghost/issue/AP-1095
- Changed posts to use ap_id_hash index to improve query performance.

Changed posts query to use ap_id_hash index

---

migrate/migrations/000042_add-generated-columns-and-indexes-to-keyvalue-table.up.sql

ref https://linear.app/ghost/issue/AP-1095
- Improve query performance by adding indexes and changing queries to use those indexes. This is a fix from the previous commit.

Fix generated columns and indexes to keyvalue

---

features/block.feature
features/step_definitions/stepdefs.js
src/activity-dispatchers/reject.dispatcher.ts
src/activity-handlers/follow.handler.ts
src/app.ts

Added functionality to reject follow requests when the follower has been blocked by the account being requested to follow

Added follow rejection when account is blocked

---

Dockerfile
boottime.sh
package.json
src/app.ts
src/instrumentation.ts

closes https://linear.app/ghost/issue/PROD-675
- Added a main function as a starting point. Introduced several setup* functions on the main function.
- Improved boot time by bundling the app in a single file. This avoids reading multiple files from disk, which slows down the booting process.

Changed app boot process

---

src/app.ts
src/http/api/block.ts

ref https://linear.app/ghost/issue/PROD-697
This allows us to start wiring up to the frontend early, whilst we still build out the backend.

Stubbed API for /block/domain & /unblock/domain

---

Dockerfile
boottime.sh
package.json
src/app.ts

ref https://linear.app/ghost/issue/PROD-675
- Revert improve boot time as it prevented image uploads. Cause is unclear at the moment.
- GitHub issue: https://github.com/googleapis/nodejs-storage/issues/2191

Revert improve boot time

---

migrate/migrations/000046_add-domain-blocks-table.down.sql
migrate/migrations/000046_add-domain-blocks-table.up.sql
src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/account/account.repository.knex.ts
src/account/account.service.ts
src/account/domain-blocked.event.ts
src/account/domain-unblocked.event.ts
src/http/api/__snapshots__/views/AccountView.viewByApId.internal-no-context.json
src/http/api/__snapshots__/views/AccountView.viewById.no-context.json
src/http/api/block.ts
src/http/api/types.ts
src/http/api/views/account.view.ts

ref https://linear.app/ghost/issue/PROD-697

Wired up `/block/domain` & `/unblock/domain` to the DB

---

migrate/migrations/000049_add-domain-hash-to-domain-blocks-table.down.sql
migrate/migrations/000049_add-domain-hash-to-domain-blocks-table.up.sql
src/moderation/moderation.service.integration.test.ts
src/moderation/moderation.service.ts

ref https://linear.app/ghost/issue/PROD-697
Now that we have domain blocks we need to make sure that we check for the blocks when moderating interations.

Restricted interations from accounts blocked by domain

---

src/account/account.repository.knex.integration.test.ts
src/account/account.repository.knex.ts
src/moderation/moderation.service.integration.test.ts
src/moderation/moderation.service.ts
src/test/fixtures.ts

ref https://linear.app/ghost/issue/PROD-697

Protected feeds and notifications from blocked domains

---

migrate/migrations/000050_add-mentions-table.down.sql
migrate/migrations/000050_add-mentions-table.up.sql

Ref https://linear.app/ghost/issue/PROD-1735/
- Added a Mentions table, with references to the post that contained the mention and the mentioned account, who was mentioned

Added `mentions` table

---

src/http/api/notification.ts
src/http/api/types.ts
src/notification/notification.service.ts

Ref https://linear.app/ghost/issue/PROD-1735
- We want to send a notification when someone is mentioned in a post. Added a new notification type for mentions.

Added mention to notification type

---

src/account/account.service.ts
src/activity-handlers/create.handler.ts

ref https://linear.app/ghost/issue/PROD-1587
- Wrapped code in a try/catch block and avoided throwing errors on ETIMEOUT or EHOSTUNREACH.

Fixed fetch failed errors

---

features/handle-mention.feature
features/step_definitions/activitypub_steps.js
features/support/fixtures.js
src/post/post.entity.ts
src/post/post.entity.unit.test.ts
src/post/post.service.ts

ref https://linear.app/ghost/issue/PROD-698
- we currently don't alter the incoming note: if it doesn't contain a properly formed hyperlink, it will not render as link in the feed

Handled incoming mentions

---

src/notification/notification-event.service.ts
src/notification/notification-event.service.unit.test.ts
src/notification/notification.service.integration.test.ts
src/notification/notification.service.ts
src/test/fixtures.ts

Ref https://linear.app/ghost/issue/PROD-1764
- Removes all notifications for a post on PostDeletedEvent

Remove notifications when a post is deleted

---

migrate/migrations/000052_add-index-on-posts-table.down.sql
migrate/migrations/000052_add-index-on-posts-table.up.sql

ref no-issue
- Added index on posts to speed up analytics query on metabase.

Added index on posts table

---

features/5xx-regressions.feature
features/step_definitions/5xx_steps.js
src/app.ts

We want a place to write these tests so that we can replicate and fix the 500 errors we're seeing. These tests capture our current largest producer in prod.

Added regression tests for 5xx errors

---

features/like-activity.feature
features/step_definitions/activitypub_steps.js
features/step_definitions/like_steps.js
features/support/inbox.js
src/activity-handlers/delete.handler.ts
src/handlers.ts
src/http/api/like.ts
src/http/api/post.ts

ref https://linear.app/ghost/issue/PROD-1734/drop-support-for-liked-collection-until-ga
- we are dropping support for the Liked collection until GA, as it relies on the legacy key-value store and we don't have appetite to migrate it to the new database structure before GA

Removed writes to the Liked collection

---

features/support/inbox.js

Removed leftover console.log

---

src/http/api/views/account.posts.view.ts

Ref https://linear.app/ghost/issue/PROD-1846
- When posts are fetched by remote lookup, the mentions in the content will not have `data-profile` attribute so the profile would not open up in our profile viewer
- Modified the content of post when fetched by remote lookup to add `data-profile` attribute in mentioned links

Modified content of post while fetching by remote lookup

---

docker-compose.yml
package.json

closes https://linear.app/ghost/issue/PROD-1840
- Enabled debugger with DAP (Debugger Adapter Protocol) to set breakpoints, see variables values and type live code in the repl.

Enabled debugger

---

jobs/cleanup-expired-key-value-records/cleanup-expired-key-value-records

ref https://linear.app/ghost/issue/PROD-685
We want to clear out the existing keys first, so we can run this job on a loop until it is done, afterwards we can switch back to cleaning up expired keys.

Updated cleanup job to focus on existing rows

---

migrate/migrations/000055_recreate-outboxes-table.down.sql
migrate/migrations/000055_recreate-outboxes-table.up.sql

Ref https://linear.app/ghost/issue/PROD-1877/
- Drops existing `outboxes` table
- Added `account_id` instead of `user_id`
- Added unique constraint to avoid duplication
- Added index for filtering and ordering

Updated `outboxes` table

---

src/storage/gcloud-storage/gcp-storage.service.ts
src/storage/gcloud-storage/gcp-storage.service.unit.test.ts

- Added automatic EXIF-based rotation using Sharp's rotate() method to fix 90-degree rotation issue with iPhone photos
- Added HEIC/HEIF formats to allowed image types
- Converted HEIC/HEIF images to JPEG format for web compatibility

Handled EXIF orientation for image uploads and added HEIC support

---

src/app.ts

closes https://linear.app/ghost/issue/PROD-780
- Changed `getKey` function to cache `jwks.json` files. We do not change this in Ghost and so it doesn't make sense to fetch them every time. If we do need to invalidate them, the `key` contains a `cachedJwks` prefix, which we can use to delete records from the KV store.

Cached jwks

---

src/http/api/views/reply.chain.view.integration.test.ts
src/http/api/views/reply.chain.view.ts

If the ancestors array is empty, `hasMore` will be true as undefined !== null

Fixed `hasMore` when ancestors is empty

---

src/http/api/account.ts

no-issue
- lookupAPIdByHandle is deprecated
- Updated the code in `account.ts` to use `lookupActorProfile` instead of `lookupAPIdByHandle`

Updated account controller to use `lookupActorProfile` instead of deprecated `lookupAPIdByHandle`

---

src/http/api/follow.ts

no-issue
- lookupAPIdByHandle is deprecated
- Updated the code in `follow.ts` to use `lookupActorProfile` instead of `lookupAPIdByHandle`

Updated follow controller to use lookupActorProfile instead of deprecated lookupAPIdByHandle

---

features/notifications.feature
features/step_definitions/notifications_steps.js
features/support/notifications.js
src/app.ts
src/http/api/notification.ts
src/notification/notification.service.ts

closes https://linear.app/ghost/issue/PROD-2002/
- We want to show a count of unread notifications to the user on AP UI

Added API endpoint for count of unread notifications

---

migrate/migrations/000058_add-index-on-notifications-table.down.sql
migrate/migrations/000058_add-index-on-notifications-table.up.sql

ref https://linear.app/ghost/issue/PROD-2001/
- Need this index for getting the unread notifications count and marking notifications as read

Added index on notifications table

---

features/notifications.feature
features/step_definitions/notifications_steps.js
src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/account/account.repository.knex.ts
src/account/account.service.ts
src/account/account.service.unit.test.ts
src/account/notifications-read-event.ts
src/app.ts
src/http/api/notification.ts
src/notification/notification-event.service.ts
src/notification/notification-event.service.unit.test.ts
src/notification/notification.service.integration.test.ts
src/notification/notification.service.ts

closes https://linear.app/ghost/issue/PROD-2004/

Added API endpoint for resetting unread notifications count

---

.github/workflows/cicd.yml

ref no-issue
- Removed staging ci/cd tests in ephemeral deployments.

Removed staging ci/cd tests in ephemeral deployments

---

src/post/post.repository.knex.integration.test.ts
src/post/post.repository.knex.ts

no issue
- Refactored code for converting a post row into post entity into a separate method. To avoid duplicate code.

Added mapRowToPostEntity method in post repository

---

.github/renovate.json

ref https://linear.app/ghost/issue/PROD-2078
- apply renovate's automerge config to cedar/** and jobs/** too

Updated renovate config to auto-merge dependencies from cedar and jobs too

---

src/configuration/registrations.ts

no issue
- Replaced manual parameter specifications with direct function references

Simplified dependency injection registrations

---

src/dispatchers.ts

Fixed linting

---

src/dispatchers.ts
src/dispatchers.unit.test.ts
src/helpers/activitypub/activity.ts
src/helpers/activitypub/activity.unit.test.ts
src/http/api/repost.ts
src/post/post.repository.knex.ts
src/post/post.service.integration.test.ts

ref https://linear.app/ghost/issue/PROD-2105/
- This adds the reposts to the outbox of Ghost's AP accounts
- Using outbox type from the outboxes table to differentiate between original posts and reposts

Added reposts to outbox

---

src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/account/account.repository.knex.integration.test.ts
src/account/events/account-created.event.ts
src/account/events/index.ts

no-issue
This will allow us to add hooks when new accounts are created.

Added AccountCreatedEvent to AccountEntity

---

docker-compose.yml
features/create-note.feature
features/create-reply.feature
nginx/server.conf
src/configuration/registrations.ts
src/storage/adapters/gcp-storage-adapter.ts
src/storage/adapters/gcp-storage-adapter.unit.test.ts
src/storage/image-storage.service.integration.test.ts

ref https://linear.app/ghost/issue/PROD-2142/
Current state:-

Added nginx proxy to local gcs images

---

jobs/populate-explore-json/index.ts

This matches how we handle handles in the main app

Stripped www. from handles in explore json

---

src/account/account.entity.ts
src/account/account.entity.unit.test.ts
src/account/account.service.ts
src/account/account.service.unit.test.ts
src/activity-handlers/update.handler.ts
src/app.ts
src/configuration/registrations.ts

closes https://linear.app/ghost/issue/PROD-2173/

Added handler for Update(Person) activity

---

jobs/backfill-ghost-explore-follows/index.ts

Some of our sites are offline, which means they redirect to
offline.ghost.org, which passed our check. Now we don't follow
redirects, and we add more checks to the response to make sure it's what
we expect.

Improved preflight checks before sending Follow

---

jobs/backfill-ghost-explore-follows/index.ts

When we send a follow to Mastodon, if they haven't seen the site before,
they will make a WebFinger request and that uses the non-www host. In
certain cases, when redirects or SSL aren't configured correctly, that
fails and causes Mastodon to put a block on our IP.

Checked non-www host can be connected to

---

src/post/post.service.ts

no issue
- We need to remove sentry errors that are redundant
- Removed errors for un-supported post type
- Removed error when author is not found
- Kept error logging in place for debugging

Cleaned up sentry errors

---

src/activity-handlers/delete.handler.ts
src/http/api/post.controller.ts
src/post/post.service.integration.test.ts
src/post/post.service.ts

no issue
- We want to move the deletion logic from controller to service so that it can be reused in handlers
- No functional change

Moved post deletion logic to post service

---

features/account-update.feature
features/account.feature
features/delete-post.feature
features/feed.feature
features/handle-delete.feature
features/notifications.feature
features/profile-liked-post.feature
features/profile-posts.feature
features/site-data.feature
features/step_definitions/block_steps.js
features/step_definitions/follow_steps.js
features/step_definitions/like_steps.js
features/step_definitions/note_steps.js
features/step_definitions/notifications_steps.js
features/step_definitions/reply_steps.js
features/step_definitions/repost_steps.js
features/step_definitions/site_steps.js
features/upload-image.feature
src/app.ts
src/configuration/registrations.ts
src/http/api/account.controller.ts
src/http/api/block.controller.ts
src/http/api/feed.controller.ts
src/http/api/follow.controller.ts
src/http/api/like.controller.ts
src/http/api/media.controller.ts
src/http/api/notification.controller.ts
src/http/api/post.controller.ts
src/http/api/reply-chain.controller.ts
src/http/api/search.controller.ts

ref https://linear.app/ghost/issue/PROD-2224
We want to make sure that we're able to make breaking changes to the API endpoints and adding the version to the path helps with that.
Note that AP endpoints are unversioned, as they adhere to the AP spec.

Added /v1 routes

---

src/helpers/activitypub/activity.ts

no issue
- Separated out logic for creating Fedify Object for Post in a method so that it can be used for creating update activity

Refactored Activity helper

---

src/activitypub/fediverse-bridge.unit.test.ts

no issue
- cleaned up duplicate creation of FediverseBridge object

Cleaned up fediverse bridge unit tests

---

package.json
yarn.lock

ref https://linear.app/ghost/issue/PROD-2307
This fixes a bug in doubleKnock which was causing error noise

Bumped fedify to 1.7.5

---

Dockerfile
package.json
src/instrumentation.ts
yarn.lock

ref https://linear.app/ghost/issue/PROD-2314
- Sends CPU profiles to GCP.

Added CPU profiler

---

src/mq/gcloud-pubsub-push/error-utils.ts
src/mq/gcloud-pubsub-push/error-utils.unit.test.ts
tsconfig.json

no ref
Added additional error analysis for network connectivity related errors as well as adding additional checks for SSL errors

Added additional error analysis

---

src/knex.kvstore.ts

Extract JSON.stringify(key) calls into a private keyToString() method to prepare for conditional key generation logic. This creates a single point of control for key serialization across all KvStore operations.

Extracted KvStroe key serialization into method

---

src/http/middleware/role-guard.ts

Sometimes we run into issues fetching the JWKS and we are just throwing, which causes a 500 and alerts in our monitoring. Seeing as the errors are due to the client calling us, we should catch them and respond 4xx

Handled errors when fetching JWKS

---

src/app.ts
src/http/api/site.controller.ts

ref https://linear.app/ghost/issue/PROD-2351
Added a new endpoint that will get called when activitypub is disabled within Ghost

Added endpoint to disable a site

---

docker-compose.yml
src/configuration/registrations.ts
src/redis.kvstore.ts

ref
https://linear.app/ghost/issue/PROD-2439/use-redis-for-fedifys-kvstore
- Addedd support for redis cluster configuration

Added redis cluster configuration

---

.github/workflows/cicd.yml

ref no-issue
- Changed concurrency settings on main to be sequential, other branches to cancel previous and deploy current commit

Changed ci/cd concurrency

---

src/configuration/registrations.ts

no ref
Lookup data in Redis KV store, and if it does not exist, fallback to the knex db store

Hotfix for Redis KVStore fallback

---

.github/workflows/cicd.yml

ref no-issue
- Label the PR with `skip-tests` to skip ci/cd tests.

Added `skip-tests` to skip ci/cd tests

---

.github/workflows/cicd.yml

ref no-issue
- Http Header: `X-ActivityPub-Commit`, value: <PR commit sha>

Added `X-ActivityPub-Commit` to staging envs

---

.github/workflows/build.yml
.github/workflows/cicd.yml

ref no-issue
- Added inherit secrets.

Fixed build secrets

---

.github/workflows/push.yml

ref no-issue
- Fixed issues in ghr push.

Fixed ghr push

---

.github/workflows/build.yml

ref no-issue
- Speed up the cicd run.

Added if on auth gcp for cicd

---

docs/env-vars.md
src/db.ts

ref https://linear.app/ghost/issue/PROD-2530
Added explicit configuration for all tarn.js connection pool options to help diagnose and resolve infrastructure issues. This allows us to align the pool settings with our MySQL server configuration and provides better control over connection lifecycle, timeouts, and resource management.

Supported env config for db connection pool

---

src/db.ts

ref https://linear.app/ghost/issue/PROD-2530
We're pretty sure that the connection pool idle time was the cause of the connection lost errors, but we want to add some extra information to the errors, if this does crop up again, we'll have more information about the current state of the system.
This code is not long term and will be removed once we're confident that the connection errors are solved.

Included pool information on Connection lost error

---

docs/one-off-jobs.md
jobs/README.md
jobs/__template__/Dockerfile
jobs/__template__/README.md
jobs/__template__/docker-compose.yml
jobs/__template__/gcloud-push.sh
jobs/__template__/index.test.ts
jobs/__template__/index.ts
jobs/__template__/run-tests.sh
jobs/new.sh

no ref
Added a template to facilitate the creation of new jobs

Added one-off job template

---

.github/workflows/deploy.yml

ref no-issue
- Make production deployment dependent on staging deployment.

Changed deployment dependencies

---

.github/workflows/deploy.yml

ref https://linear.app/ghost/issue/PROD-2681
- Changed cicd to account for the GCP project split

Changed cicd to reflect two GCP accounts
